In [68]:
import pandas as pd
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [85]:
rod_df = pd.read_excel("rod_prepared_data.xlsx", sheet_name=0)
rod_df = rod_df.drop(["HOTEL_LAT", "HOTEL_LON"], axis = 1)

print(rod_df.shape)
rod_df

(7, 43)

,HOTEL_NAME,etape_rod__1_informations_generales__sous_etape_rod__donnees_admin__data__nb_de_chambres,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__bar,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__restaurant,etape_rod__2_services_equipements__sous_etape_rod__f_b__data__minibar,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__salles_de_reunion,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__salle_de_sport,etape_rod__2_services_equipements__sous_etape_rod__non_f_b__data__piscine,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__vitrine_refrigeree,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__micro_ondes,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__fontaine_a_eau,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__machine_a_cafe,etape_rod__2_services_equipements__sous_etape_rod__dispo_dans_le_lobby__data__bouilloire,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_couples,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_amis,etape_rod__3_profil_de_vos_clients__sous_etape_rod__loisirs__data__top_1_familles,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__boissons_alcoolisees,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__produits_sales_frais,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__produits_sucres_frais,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_f_b__data__epicerie_fine,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__produits_cosmetiques,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__articles_pour_enfants,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__pret_a_porter,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__accessoires,etape_rod__3_profil_de_vos_clients__sous_etape_rod__besoins_de_vos_clients_non_f_b__data__souvenirs,etape_rod__4_informations_corner__sous_etape_rod__corner_de_vente_actuel__data__votre_hotel_dispose_t_il_deja_d_un_corner_de_vente,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__liste_des_produits_f_b__source_row__85,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__reception,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__snacking_comptoir,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__distributeur_auto,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_f_b__data__hotel_staff,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__liste_des_produits_non_f_b__source_row__99,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__reception,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__distributeur_auto,etape_rod__4_informations_corner__sous_etape_rod__votre_corner_actuel_offre_non_f_b__data__hotel_staff,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__wifi__source_row__122,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__internet_filaire_prise_rj45__source_row__123,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__alimentation_electrique__source_row__124,etape_rod__4_informations_corner__sous_etape_rod__equipements_disponibles__data__videosurveillance__source_row__125,IBIS BUDGET,IBIS STYLES,MERCURE,NOVOTEL
0,Ibis budget Nice,129,0,0,0,4,0,0,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0
1,Ibis budget Strasbourg Centre République,97,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0
2,IBIS STYLES ROISSY CDG,309,1,1,0,1,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,0,0
3,Novotel Megève Mont-Blanc,572,1,1,0,3,2,1,0,0,0,0,0,0,0,1,1,0,0,1,1,1,1,1,1,0,0,1,0,0,1,1,1,0,1,0,0,0,0,0,0,0,1
4,Novotel Paris Tour Eiffel,764,1,3,0,36,1,1,0,0,1,1,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
5,Mercure Paris Montmartre Sacré-Cœur,305,0,1,0,1,1,0,1,0,0,0,0,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0
6,MERCURE PARIS BOULOGNE,191,1,2,0,13,1,1,1,0,1,0,0,1,0,0,1,1,1,0,0,0,0,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0

In [86]:
poi_df = pd.read_excel("poi_prepared_data.xlsx", sheet_name=0)
print(poi_df.shape)
poi_df

(6, 13)

,HOTEL_NAME,HOTEL_LAT,HOTEL_LON,fb_0_1km,fb_0_2km,fb_0_3km,fb_0_4km,fb_0_5km,not_fb_0_1km,not_fb_0_2km,not_fb_0_3km,not_fb_0_4km,not_fb_0_5km
0,Ibis budget Nice,43.667571,7.214308,0,0,0,3,3,3,3,6,6,6
1,Ibis budget Strasbourg Centre République,48.585058,7.736591,0,30,60,102,120,0,3,3,24,36
2,Mercure Paris Montmartre Sacré-Cœur,48.885240,2.330055,6,12,57,123,195,3,3,27,45,54
3,Novotel Megève Mont-Blanc,45.859850,6.619478,3,3,6,6,15,0,0,3,3,3
4,Novotel Paris Tour Eiffel,48.849660,2.283704,3,6,9,36,69,0,9,12,15,18
5,Novotel Porte d’Italie,48.819054,2.359406,9,18,21,42,75,3,3,3,6,9

In [87]:
weather_df = pd.read_excel("weather_prepared_data.xlsx", sheet_name=0)
print(weather_df.shape)
weather_df.head(3)

(5, 5117)

   HOTEL_LAT  HOTEL_LON  m01_dwpt_max  m01_dwpt_max.1  m01_dwpt_max.2  \
0  43.667571   7.214308          11.7            13.8            10.1
1  45.859850   6.619478           7.8             7.3             2.1
2  48.585058   7.736591          10.9            10.1             8.1

   m01_dwpt_max.3  m01_dwpt_max.4  m01_dwpt_max.5  m01_dwpt_max.6  \
0            11.7            13.8            10.1            11.7
1             7.8             7.3             2.1             7.8
2            10.9            10.1             8.1            10.9

   m01_dwpt_max.7  m01_dwpt_max.8  m01_dwpt_mean  m01_dwpt_mean.1  \
0            13.8            10.1       4.190188         4.944220
1             7.3             2.1      -4.595161        -5.025941
2            10.1             8.1       0.284812         0.931855

   m01_dwpt_mean.2  m01_dwpt_mean.3  m01_dwpt_mean.4  m01_dwpt_mean.5  \
0         2.316801         4.190188         4.944220         2.316801
1        -6.830242        -4.595161        -5.025941        -6.830242
2        -0.064382         0.284812         0.931855        -0.064382

   m01_dwpt_mean.6  m01_dwpt_mean.7  m01_dwpt_mean.8  m01_dwpt_median  \
0         4.190188         4.944220         2.316801             4.85
1        -4.595161        -5.025941        -6.830242            -3.00
2         0.284812         0.931855        -0.064382             0.00

   m01_dwpt_median.1  m01_dwpt_median.2  m01_dwpt_median.3  m01_dwpt_median.4  \
0                6.0                3.1               4.85                6.0
1               -3.4               -4.8              -3.00               -3.4
2                0.1                0.0               0.00                0.1

   m01_dwpt_median.5  m01_dwpt_median.6  m01_dwpt_median.7  m01_dwpt_median.8  \
0                3.1               4.85                6.0                3.1
1               -4.8              -3.00               -3.4               -4.8
2                0.0               0.00                0.1                0.0

   m01_dwpt_min  m01_dwpt_min.1  m01_dwpt_min.2  m01_dwpt_min.3  \
0          -7.7            -7.8           -11.7            -7.7
1         -29.7           -23.9           -27.9           -29.7
2          -9.8            -6.0           -11.1            -9.8

   m01_dwpt_min.4  m01_dwpt_min.5  m01_dwpt_min.6  m01_dwpt_min.7  \
0            -7.8           -11.7            -7.7            -7.8
1           -23.9           -27.9           -29.7           -23.9
2            -6.0           -11.1            -9.8            -6.0

   m01_dwpt_min.8  m01_dwpt_q25  m01_dwpt_q25.1  m01_dwpt_q25.2  \
0           -11.7          2.10             2.7          -0.900
1           -27.9         -7.65            -9.5         -10.325
2           -11.1         -4.30            -1.4          -2.000

   m01_dwpt_q25.3  m01_dwpt_q25.4  m01_dwpt_q25.5  m01_dwpt_q25.6  \
0            2.10             2.7          -0.900            2.10
1           -7.65            -9.5         -10.325           -7.65
2           -4.30            -1.4          -2.000           -4.30

   m01_dwpt_q25.7  m01_dwpt_q25.8  m01_dwpt_q75  m01_dwpt_q75.1  \
0             2.7          -0.900         6.900             8.0
1            -9.5         -10.325         0.500             0.6
2            -1.4          -2.000         4.825             3.1

   m01_dwpt_q75.2  m01_dwpt_q75.3  m01_dwpt_q75.4  m01_dwpt_q75.5  \
0             6.0           6.900             8.0             6.0
1            -2.0           0.500             0.6            -2.0
2             3.0           4.825             3.1             3.0

   m01_dwpt_q75.6  m01_dwpt_q75.7  m01_dwpt_q75.8  m01_index  m01_index.1  \
0           6.900             8.0             6.0          5           17
1           0.500             0.6            -2.0         38           50
2           4.825             3.1             3.0         71           83

   m01_index.2  m01_index.3  m01_index.4  m01_index.5  m01_index.6  \
0           29            5           17           29            5
1           62           38           50           62           38
2           95           71           83           95           71

   m01_index.7  m01_index.8  m01_prcp_max  m01_prcp_max.1  m01_prcp_max.2  \
0           17           29           8.0            24.9             5.2
1           50           62           4.3             7.9             4.1
2           83           95           2.6             3.0             2.2

   m01_prcp_max.3  m01_prcp_max.4  m01_prcp_max.5  m01_prcp_max.6  \
0             8.0            24.9             5.2             8.0
1             4.3             7.9             4.1             4.3
2             2.6             3.0             2.2             2.6

   m01_prcp_max.7  m01_prcp_max.8  m01_prcp_mean  m01_prcp_mean.1  \
0            24.9             5.2       0.091263         0.201344
1             7.9             4.1       0.229435         0.342339
2             3.0             2.2       0.059274         0.099462

   m01_prcp_mean.2  m01_prcp_mean.3  m01_prcp_mean.4  m01_prcp_mean.5  \
0         0.126075         0.091263         0.201344         0.126075
1         0.183871         0.229435         0.342339         0.183871
2         0.075806         0.059274         0.099462         0.075806

   m01_prcp_mean.6  m01_prcp_mean.7  m01_prcp_mean.8  m01_prcp_median  \
0         0.091263         0.201344         0.126075                0
1         0.229435         0.342339         0.183871                0
2         0.059274         0.099462         0.075806                0

   m01_prcp_median.1  m01_prcp_median.2  m01_prcp_median.3  m01_prcp_median.4  \
0                  0                  0                  0                  0
1                  0                  0                  0                  0
2                  0                  0                  0                  0

   m01_prcp_median.5  m01_prcp_median.6  m01_prcp_median.7  m01_prcp_median.8  \
0                  0                  0                  0                  0
1                  0                  0                  0                  0
2                  0                  0                  0                  0

   m01_prcp_min  m01_prcp_min.1  m01_prcp_min.2  m01_prcp_min.3  \
0             0               0               0               0
1             0               0               0               0
2             0               0               0               0

   m01_prcp_min.4  m01_prcp_min.5  m01_prcp_min.6  m01_prcp_min.7  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_min.8  m01_prcp_q25  m01_prcp_q25.1  m01_prcp_q25.2  \
0               0             0               0               0
1               0             0               0               0
2               0             0               0               0

   m01_prcp_q25.3  m01_prcp_q25.4  m01_prcp_q25.5  m01_prcp_q25.6  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_q25.7  m01_prcp_q25.8  m01_prcp_q75  m01_prcp_q75.1  \
0               0               0             0             0.0
1               0               0             0             0.2
2               0               0             0             0.0

   m01_prcp_q75.2  m01_prcp_q75.3  m01_prcp_q75.4  m01_prcp_q75.5  \
0               0               0             0.0               0
1               0               0             0.2               0
2               0               0             0.0               0

   m01_prcp_q75.6  m01_prcp_q75.7  m01_prcp_q75.8  m01_pres_max  \
0               0             0.0               0        1035.9
1               0             0.2               0        1038.7
2               0             0.0               0        1039.0

   m01_pres_max.1  m01_pres_max.2  m01_pres_max.3  m01_pres_max.4  \
0          1032.4          1023.4          1035.9          1032.4
1          1033.7          1026.2          1038.7          1033.7
2          1041.9          1027.5          1039.0          1041.9

   m01_pres_max.5  m01_pres_max.6  m01_pres_max.7  m01_pres_max.8  \
0          1023.4          1035.9          1032.4          1023.4
1          1026.2          1038.7          1033.7          1026.2
2          1027.5          1039.0          1041.9          1027.5

   m01_pres_mean  m01_pres_mean.1  m01_pres_mean.2  m01_pres_mean.3  \
0    1018.031317      1017.613306      1007.990323      1018.031317
1    1020.037097      1018.511290      1010.418683      1020.037097
2    1021.235081      1018.150806      1009.160349      1021.235081

   m01_pres_mean.4  m01_pres_mean.5  m01_pres_mean.6  m01_pres_mean.7  \
0      1017.613306      1007.990323      1018.031317      1017.613306
1      1018.511290      1010.418683      1020.037097      1018.511290
2      1018.150806      1009.160349      1021.235081      1018.150806

   m01_pres_mean.8  m01_pres_median  m01_pres_median.1  m01_pres_median.2  \
0      1007.990323          1020.05            1017.85             1006.0
1      1010.418683          1020.00            1018.50             1011.9
2      1009.160349          1027.00            1019.00             1011.0

   m01_pres_median.3  m01_pres_median.4  m01_pres_median.5  m01_pres_median.6  \
0            1020.05            1017.85             1006.0            1020.05
1            1020.00            1018.50             1011.9            1020.00
2            1027.00            1019.00             1011.0            1027.00

   m01_pres_median.7  m01_pres_median.8  m01_pres_min  m01_pres_min.1  \
0            1017.85             1006.0         996.1           998.0
1            1018.50             1011.9         993.2           999.7
2            1019.00             1011.0         987.4           993.7

   m01_pres_min.2  m01_pres_min.3  m01_pres_min.4  m01_pres_min.5  \
0           989.0           996.1           998.0           989.0
1           991.5           993.2           999.7           991.5
2           991.0           987.4           993.7           991.0

   m01_pres_min.6  m01_pres_min.7  m01_pres_min.8  m01_pres_q25  \
0           996.1           998.0           989.0      1008.200
1           993.2           999.7           991.5      1011.700
2           987.4           993.7           991.0      1010.975

   m01_pres_q25.1  m01_pres_q25.2  m01_pres_q25.3  m01_pres_q25.4  \
0          1013.0          1000.0        1008.200          1013.0
1          1013.1          1001.3        1011.700          1013.1
2          1008.0          1000.3        1010.975          1008.0

   m01_pres_q25.5  m01_pres_q25.6  m01_pres_q25.7  m01_pres_q25.8  \
0          1000.0        1008.200          1013.0          1000.0
1          1001.3        1011.700          1013.1          1001.3
2          1000.3        1010.975          1008.0          1000.3

   m01_pres_q75  m01_pres_q75.1  m01_pres_q75.2  m01_pres_q75.3  \
0        1028.8          1022.0          1017.0          1028.8
1        1030.0          1024.7          1018.2          1030.0
2        1031.6          1029.0          1016.9          1031.6

   m01_pres_q75.4  m01_pres_q75.5  m01_pres_q75.6  m01_pres_q75.7  \
0          1022.0          1017.0          1028.8          1022.0
1          1024.7          1018.2          1030.0          1024.7
2          1029.0          1016.9          1031.6          1029.0

   m01_pres_q75.8  m01_rhum_max  m01_rhum_max.1  m01_rhum_max.2  \
0          1017.0            96             100             100
1          1018.2           100              99              97
2          1016.9           100             100             100

   m01_rhum_max.3  m01_rhum_max.4  m01_rhum_max.5  m01_rhum_max.6  \
0              96             100             100              96
1             100              99              97             100
2             100             100             100             100

   m01_rhum_max.7  m01_rhum_max.8  m01_rhum_mean  m01_rhum_mean.1  \
0             100             100      68.086022        69.806452
1              99              97      69.505376        70.672043
2             100             100      83.168011        84.180108

   m01_rhum_mean.2  m01_rhum_mean.3  m01_rhum_mean.4  m01_rhum_mean.5  \
0        63.106183        68.086022        69.806452        63.106183
1        71.147849        69.505376        70.672043        71.147849
2        88.721774        83.168011        84.180108        88.721774

   m01_rhum_mean.6  m01_rhum_mean.7  m01_rhum_mean.8  m01_rhum_median  \
0        68.086022        69.806452        63.106183               69
1        69.505376        70.672043        71.147849               84
2        83.168011        84.180108        88.721774               85

   m01_rhum_median.1  m01_rhum_median.2  m01_rhum_median.3  m01_rhum_median.4  \
0               69.5                 62                 69               69.5
1               80.0                 79                 84               80.0
2               87.0                 92                 85               87.0

   m01_rhum_median.5  m01_rhum_median.6  m01_rhum_median.7  m01_rhum_median.8  \
0                 62                 69               69.5                 62
1                 79                 84               80.0                 79
2                 92                 85               87.0                 92

   m01_rhum_min  m01_rhum_min.1  m01_rhum_min.2  m01_rhum_min.3  \
0            24              28              17              24
1             7              16              20               7
2            54              46              56              54

   m01_rhum_min.4  m01_rhum_min.5  m01_rhum_min.6  m01_rhum_min.7  \
0              28              17              24              28
1              16              20               7              16
2              46              56              54              46

   m01_rhum_min.8  m01_rhum_q25  m01_rhum_q25.1  m01_rhum_q25.2  \
0              17         61.00           58.75              53
1              20         45.75           54.00              56
2              56         74.00           76.00              83

   m01_rhum_q25.3  m01_rhum_q25.4  m01_rhum_q25.5  m01_rhum_q25.6  \
0           61.00           58.75              53           61.00
1           45.75           54.00              56           45.75
2           74.00           76.00              83           74.00

   m01_rhum_q25.7  m01_rhum_q25.8  m01_rhum_q75  m01_rhum_q75.1  \
0           58.75              53            78           83.00
1           54.00              56            93           90.00
2           76.00              83            92           94.25

   m01_rhum_q75.2  m01_rhum_q75.3  m01_rhum_q75.4  m01_rhum_q75.5  \
0              76              78           83.00              76
1              87              93           90.00              87
2              96              92           94.25              96

   m01_rhum_q75.6  m01_rhum_q75.7  m01_rhum_q75.8  m01_snow_max  \
0              78           83.00              76           0.0
1              93           90.00              87           NaN
2              92           94.25              96           0.0

   m01_snow_max.1  m01_snow_max.2  m01_snow_max.3  m01_snow_max.4  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             4.0             2.0             0.0             4.0

   m01_snow_max.5  m01_snow_max.6  m01_snow_max.7  m01_snow_max.8  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             2.0             0.0             4.0             2.0

   m01_snow_mean  m01_snow_mean.1  m01_snow_mean.2  m01_snow_mean.3  \
0            0.0         0.000000         0.000000              0.0
1            NaN              NaN              NaN              NaN
2            0.0         0.028226         0.052419              0.0

   m01_snow_mean.4  m01_snow_mean.5  m01_snow_mean.6  m01_snow_mean.7  \
0         0.000000         0.000000              0.0         0.000000
1              NaN              NaN              NaN              NaN
2         0.028226         0.052419              0.0         0.028226

   m01_snow_mean.8  m01_snow_median  m01_snow_median.1  m01_snow_median.2  \
0         0.000000              0.0                0.0                0.0
1              NaN              NaN                NaN                NaN
2         0.052419              0.0                0.0                0.0

   m01_snow_median.3  m01_snow_median.4  m01_snow_median.5  m01_snow_median.6  \
0                0.0                0.0                0.0                0.0
1                NaN                NaN                NaN                NaN
2                0.0                0.0                0.0                0.0

   m01_snow_median.7  m01_snow_median.8  m01_snow_min  m01_snow_min.1  \
0                0.0                0.0           0.0             0.0
1                NaN                NaN           NaN             NaN
2                0.0                0.0           0.0             0.0

   m01_snow_min.2  m01_snow_min.3  m01_snow_min.4  m01_snow_min.5  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             0.0             0.0             0.0             0.0

   m01_snow_min.6  m01_snow_min.7  m01_snow_min.8  m01_snow_q25  \
0             0.0             0.0             0.0           0.0
1             NaN             NaN             NaN           NaN
2             0.0             0.0             0.0           0.0

   m01_snow_q25.1  m01_snow_q25.2  m01_snow_q25.3  m01_snow_q25.4  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             0.0             0.0             0.0             0.0

   m01_snow_q25.5  m01_snow_q25.6  m01_snow_q25.7  m01_snow_q25.8  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             0.0             0.0             0.0             0.0

   m01_snow_q75  m01_snow_q75.1  m01_snow_q75.2  m01_snow_q75.3  \
0           0.0             0.0             0.0             0.0
1           NaN             NaN             NaN             NaN
2           0.0             0.0             0.0             0.0

   m01_snow_q75.4  m01_snow_q75.5  m01_snow_q75.6  m01_snow_q75.7  \
0             0.0             0.0             0.0             0.0
1             NaN             NaN             NaN             NaN
2             0.0             0.0             0.0             0.0

   m01_snow_q75.8  m01_temp_max  m01_temp_max.1  m01_temp_max.2  \
0             0.0          19.6            18.9            16.0
1             NaN          12.3             9.8             8.1
2             0.0          14.5            17.0            14.0

   m01_temp_max.3  m01_temp_max.4  m01_temp_max.5  m01_temp_max.6  \
0            19.6            18.9            16.0            19.6
1            12.3             9.8             8.1            12.3
2            14.5            17.0            14.0            14.5

   m01_temp_max.7  m01_temp_max.8  m01_temp_mean  m01_temp_mean.1  \
0            18.9            16.0      10.068145        10.603898
1             9.8             8.1       1.927823         0.622849
2            17.0            14.0       2.990054         3.573522

   m01_temp_mean.2  m01_temp_mean.3  m01_temp_mean.4  m01_temp_mean.5  \

In [88]:
transaction_df = pd.read_excel("transaction_prepared_data.xlsx", sheet_name=0)
print(transaction_df.shape)
transaction_df

(5, 290)

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,m01__FB__ALCOOL__montant,m01__FB__ALCOOL__nbr_ventes,m01__FB__FOOD_SALEE__montant,m01__FB__FOOD_SALEE__nbr_ventes,m01__FB__FOOD_SUCREE__montant,m01__FB__FOOD_SUCREE__nbr_ventes,m01__FB__SANS_ALCOOL__montant,m01__FB__SANS_ALCOOL__nbr_ventes,m01__FB__SOUVENIRS__montant,m01__FB__SOUVENIRS__nbr_ventes,m01__NON_FB__ACCESSOIRES__montant,m01__NON_FB__ACCESSOIRES__nbr_ventes,m01__NON_FB__COSMETIQUE__montant,m01__NON_FB__COSMETIQUE__nbr_ventes,m01__NON_FB__JEUX_ENFANTS__montant,m01__NON_FB__JEUX_ENFANTS__nbr_ventes,m01__NON_FB__ND__montant,m01__NON_FB__ND__nbr_ventes,m01__NON_FB__PAP__montant,m01__NON_FB__PAP__nbr_ventes,m01__NON_FB__SOS__montant,m01__NON_FB__SOS__nbr_ventes,m01__NON_FB__SOUVENIRS__montant,m01__NON_FB__SOUVENIRS__nbr_ventes,m02__FB__ALCOOL__montant,m02__FB__ALCOOL__nbr_ventes,m02__FB__FOOD_SALEE__montant,m02__FB__FOOD_SALEE__nbr_ventes,m02__FB__FOOD_SUCREE__montant,m02__FB__FOOD_SUCREE__nbr_ventes,m02__FB__SANS_ALCOOL__montant,m02__FB__SANS_ALCOOL__nbr_ventes,m02__FB__SOUVENIRS__montant,m02__FB__SOUVENIRS__nbr_ventes,m02__NON_FB__ACCESSOIRES__montant,m02__NON_FB__ACCESSOIRES__nbr_ventes,m02__NON_FB__COSMETIQUE__montant,m02__NON_FB__COSMETIQUE__nbr_ventes,m02__NON_FB__JEUX_ENFANTS__montant,m02__NON_FB__JEUX_ENFANTS__nbr_ventes,m02__NON_FB__ND__montant,m02__NON_FB__ND__nbr_ventes,m02__NON_FB__PAP__montant,m02__NON_FB__PAP__nbr_ventes,m02__NON_FB__SOS__montant,m02__NON_FB__SOS__nbr_ventes,m02__NON_FB__SOUVENIRS__montant,m02__NON_FB__SOUVENIRS__nbr_ventes,m03__FB__ALCOOL__montant,m03__FB__ALCOOL__nbr_ventes,m03__FB__FOOD_SALEE__montant,m03__FB__FOOD_SALEE__nbr_ventes,m03__FB__FOOD_SUCREE__montant,m03__FB__FOOD_SUCREE__nbr_ventes,m03__FB__SANS_ALCOOL__montant,m03__FB__SANS_ALCOOL__nbr_ventes,m03__FB__SOUVENIRS__montant,m03__FB__SOUVENIRS__nbr_ventes,m03__NON_FB__ACCESSOIRES__montant,m03__NON_FB__ACCESSOIRES__nbr_ventes,m03__NON_FB__COSMETIQUE__montant,m03__NON_FB__COSMETIQUE__nbr_ventes,m03__NON_FB__JEUX_ENFANTS__montant,m03__NON_FB__JEUX_ENFANTS__nbr_ventes,m03__NON_FB__ND__montant,m03__NON_FB__ND__nbr_ventes,m03__NON_FB__PAP__montant,m03__NON_FB__PAP__nbr_ventes,m03__NON_FB__SOS__montant,m03__NON_FB__SOS__nbr_ventes,m03__NON_FB__SOUVENIRS__montant,m03__NON_FB__SOUVENIRS__nbr_ventes,m04__FB__ALCOOL__montant,m04__FB__ALCOOL__nbr_ventes,m04__FB__FOOD_SALEE__montant,m04__FB__FOOD_SALEE__nbr_ventes,m04__FB__FOOD_SUCREE__montant,m04__FB__FOOD_SUCREE__nbr_ventes,m04__FB__SANS_ALCOOL__montant,m04__FB__SANS_ALCOOL__nbr_ventes,m04__FB__SOUVENIRS__montant,m04__FB__SOUVENIRS__nbr_ventes,m04__NON_FB__ACCESSOIRES__montant,m04__NON_FB__ACCESSOIRES__nbr_ventes,m04__NON_FB__COSMETIQUE__montant,m04__NON_FB__COSMETIQUE__nbr_ventes,m04__NON_FB__JEUX_ENFANTS__montant,m04__NON_FB__JEUX_ENFANTS__nbr_ventes,m04__NON_FB__ND__montant,m04__NON_FB__ND__nbr_ventes,m04__NON_FB__PAP__montant,m04__NON_FB__PAP__nbr_ventes,m04__NON_FB__SOS__montant,m04__NON_FB__SOS__nbr_ventes,m04__NON_FB__SOUVENIRS__montant,m04__NON_FB__SOUVENIRS__nbr_ventes,m05__FB__ALCOOL__montant,m05__FB__ALCOOL__nbr_ventes,m05__FB__FOOD_SALEE__montant,m05__FB__FOOD_SALEE__nbr_ventes,m05__FB__FOOD_SUCREE__montant,m05__FB__FOOD_SUCREE__nbr_ventes,m05__FB__SANS_ALCOOL__montant,m05__FB__SANS_ALCOOL__nbr_ventes,m05__FB__SOUVENIRS__montant,m05__FB__SOUVENIRS__nbr_ventes,m05__NON_FB__ACCESSOIRES__montant,m05__NON_FB__ACCESSOIRES__nbr_ventes,m05__NON_FB__COSMETIQUE__montant,m05__NON_FB__COSMETIQUE__nbr_ventes,m05__NON_FB__JEUX_ENFANTS__montant,m05__NON_FB__JEUX_ENFANTS__nbr_ventes,m05__NON_FB__ND__montant,m05__NON_FB__ND__nbr_ventes,m05__NON_FB__PAP__montant,m05__NON_FB__PAP__nbr_ventes,m05__NON_FB__SOS__montant,m05__NON_FB__SOS__nbr_ventes,m05__NON_FB__SOUVENIRS__montant,m05__NON_FB__SOUVENIRS__nbr_ventes,m06__FB__ALCOOL__montant,m06__FB__ALCOOL__nbr_ventes,m06__FB__FOOD_SALEE__montant,m06__FB__FOOD_SALEE__nbr_ventes,m06__FB__FOOD_SUCREE__montant,m06__FB__FOOD_SUCREE__nbr_ventes,m06__FB__SANS_ALCOOL__montant,m06__FB__SANS_ALCOOL__nbr_ventes,m06__FB__SOUVENIRS__montant,m06__FB__SOUVENIRS__nbr_ventes,m06__NON_FB__ACCESSOIRES__montant,m06__NON_FB__ACCESSOIRES__nbr_ventes,m06__NON_FB__COSMETIQUE__montant,m06__NON_FB__COSMETIQUE__nbr_ventes,m06__NON_FB__JEUX_ENFANTS__montant,m06__NON_FB__JEUX_ENFANTS__nbr_ventes,m06__NON_FB__ND__montant,m06__NON_FB__ND__nbr_ventes,m06__NON_FB__PAP__montant,m06__NON_FB__PAP__nbr_ventes,m06__NON_FB__SOS__montant,m06__NON_FB__SOS__nbr_ventes,m06__NON_FB__SOUVENIRS__montant,m06__NON_FB__SOUVENIRS__nbr_ventes,m07__FB__ALCOOL__montant,m07__FB__ALCOOL__nbr_ventes,m07__FB__FOOD_SALEE__montant,m07__FB__FOOD_SALEE__nbr_ventes,m07__FB__FOOD_SUCREE__montant,m07__FB__FOOD_SUCREE__nbr_ventes,m07__FB__SANS_ALCOOL__montant,m07__FB__SANS_ALCOOL__nbr_ventes,m07__FB__SOUVENIRS__montant,m07__FB__SOUVENIRS__nbr_ventes,m07__NON_FB__ACCESSOIRES__montant,m07__NON_FB__ACCESSOIRES__nbr_ventes,m07__NON_FB__COSMETIQUE__montant,m07__NON_FB__COSMETIQUE__nbr_ventes,m07__NON_FB__JEUX_ENFANTS__montant,m07__NON_FB__JEUX_ENFANTS__nbr_ventes,m07__NON_FB__ND__montant,m07__NON_FB__ND__nbr_ventes,m07__NON_FB__PAP__montant,m07__NON_FB__PAP__nbr_ventes,m07__NON_FB__SOS__montant,m07__NON_FB__SOS__nbr_ventes,m07__NON_FB__SOUVENIRS__montant,m07__NON_FB__SOUVENIRS__nbr_ventes,m08__FB__ALCOOL__montant,m08__FB__ALCOOL__nbr_ventes,m08__FB__FOOD_SALEE__montant,m08__FB__FOOD_SALEE__nbr_ventes,m08__FB__FOOD_SUCREE__montant,m08__FB__FOOD_SUCREE__nbr_ventes,m08__FB__SANS_ALCOOL__montant,m08__FB__SANS_ALCOOL__nbr_ventes,m08__FB__SOUVENIRS__montant,m08__FB__SOUVENIRS__nbr_ventes,m08__NON_FB__ACCESSOIRES__montant,m08__NON_FB__ACCESSOIRES__nbr_ventes,m08__NON_FB__COSMETIQUE__montant,m08__NON_FB__COSMETIQUE__nbr_ventes,m08__NON_FB__JEUX_ENFANTS__montant,m08__NON_FB__JEUX_ENFANTS__nbr_ventes,m08__NON_FB__ND__montant,m08__NON_FB__ND__nbr_ventes,m08__NON_FB__PAP__montant,m08__NON_FB__PAP__nbr_ventes,m08__NON_FB__SOS__montant,m08__NON_FB__SOS__nbr_ventes,m08__NON_FB__SOUVENIRS__montant,m08__NON_FB__SOUVENIRS__nbr_ventes,m09__FB__ALCOOL__montant,m09__FB__ALCOOL__nbr_ventes,m09__FB__FOOD_SALEE__montant,m09__FB__FOOD_SALEE__nbr_ventes,m09__FB__FOOD_SUCREE__montant,m09__FB__FOOD_SUCREE__nbr_ventes,m09__FB__SANS_ALCOOL__montant,m09__FB__SANS_ALCOOL__nbr_ventes,m09__FB__SOUVENIRS__montant,m09__FB__SOUVENIRS__nbr_ventes,m09__NON_FB__ACCESSOIRES__montant,m09__NON_FB__ACCESSOIRES__nbr_ventes,m09__NON_FB__COSMETIQUE__montant,m09__NON_FB__COSMETIQUE__nbr_ventes,m09__NON_FB__JEUX_ENFANTS__montant,m09__NON_FB__JEUX_ENFANTS__nbr_ventes,m09__NON_FB__ND__montant,m09__NON_FB__ND__nbr_ventes,m09__NON_FB__PAP__montant,m09__NON_FB__PAP__nbr_ventes,m09__NON_FB__SOS__montant,m09__NON_FB__SOS__nbr_ventes,m09__NON_FB__SOUVENIRS__montant,m09__NON_FB__SOUVENIRS__nbr_ventes,m10__FB__ALCOOL__montant,m10__FB__ALCOOL__nbr_ventes,m10__FB__FOOD_SALEE__montant,m10__FB__FOOD_SALEE__nbr_ventes,m10__FB__FOOD_SUCREE__montant,m10__FB__FOOD_SUCREE__nbr_ventes,m10__FB__SANS_ALCOOL__montant,m10__FB__SANS_ALCOOL__nbr_ventes,m10__NON_FB__ACCESSOIRES__montant,m10__NON_FB__ACCESSOIRES__nbr_ventes,m10__NON_FB__COSMETIQUE__montant,m10__NON_FB__COSMETIQUE__nbr_ventes,m10__NON_FB__JEUX_ENFANTS__montant,m10__NON_FB__JEUX_ENFANTS__nbr_ventes,m10__NON_FB__ND__montant,m10__NON_FB__ND__nbr_ventes,m10__NON_FB__PAP__montant,m10__NON_FB__PAP__nbr_ventes,m10__NON_FB__SOS__montant,m10__NON_FB__SOS__nbr_ventes,m10__NON_FB__SOUVENIRS__montant,m10__NON_FB__SOUVENIRS__nbr_ventes,m11__FB__ALCOOL__montant,m11__FB__ALCOOL__nbr_ventes,m11__FB__FOOD_SALEE__montant,m11__FB__FOOD_SALEE__nbr_ventes,m11__FB__FOOD_SUCREE__montant,m11__FB__FOOD_SUCREE__nbr_ventes,m11__FB__SANS_ALCOOL__montant,m11__FB__SANS_ALCOOL__nbr_ventes,m11__FB__SOUVENIRS__montant,m11__FB__SOUVENIRS__nbr_ventes,m11__NON_FB__ACCESSOIRES__montant,m11__NON_FB__ACCESSOIRES__nbr_ventes,m11__NON_FB__COSMETIQUE__montant,m11__NON_FB__COSMETIQUE__nbr_ventes,m11__NON_FB__JEUX_ENFANTS__montant,m11__NON_FB__JEUX_ENFANTS__nbr_ventes,m11__NON_FB__ND__montant,m11__NON_FB__ND__nbr_ventes,m11__NON_FB__PAP__montant,m11__NON_FB__PAP__nbr_ventes,m11__NON_FB__SOS__montant,m11__NON_FB__SOS__nbr_ventes,m11__NON_FB__SOUVENIRS__montant,m11__NON_FB__SOUVENIRS__nbr_ventes,m12__FB__ALCOOL__montant,m12__FB__ALCOOL__nbr_ventes,m12__FB__FOOD_SALEE__montant,m12__FB__FOOD_SALEE__nbr_ventes,m12__FB__FOOD_SUCREE__montant,m12__FB__FOOD_SUCREE__nbr_ventes,m12__FB__SANS_ALCOOL__montant,m12__FB__SANS_ALCOOL__nbr_ventes,m12__FB__SOUVENIRS__montant,m12__FB__SOUVENIRS__nbr_ventes,m12__NON_FB__ACCESSOIRES__montant,m12__NON_FB__ACCESSOIRES__nbr_ventes,m12__NON_FB__COSMETIQUE__montant,m12__NON_FB__COSMETIQUE__nbr_ventes,m12__NON_FB__JEUX_ENFANTS__montant,m12__NON_FB__JEUX_ENFANTS__nbr_ventes,m12__NON_FB__ND__montant,m12__NON_FB__ND__nbr_ventes,m12__NON_FB__PAP__montant,m12__NON_FB__PAP__nbr_ventes,m12__NON_FB__SOS__montant,m12__NON_FB__SOS__nbr_ventes,m12__NON_FB__SOUVENIRS__montant,m12__NON_FB__SOUVENIRS__nbr_ventes
0,Ibis budget Nice,Nice,43.667571,7.214308,0,0,28.5,10,25.0,12,258.1,78,0.0,0,20,2,0.0,0,0.00,0,0,0,0,0,14,1,0.0,0,0,0,20.0,6,17.5,8,214.8,65,0,0,10,1,0.0,0,0.00,0,0,0,6,1,0.0,0,0.0,0,0,0,19.5,7,41.0,18,515.4,169,0,0,41,4,0,0,0.00,0,11,1,0,0,0,0,0,0,0,0,55.5,15,39.6,16,498.1,158,0,0,251.1,17,29.0,3,0.00,0,12,1,44,3,22,2,0,0,0,0,70.5,14,0.0,0,904.8,253,0,0,304,25,0.0,0,18.0,1,167,13,136,12,14,1,0,0,0,0,113.5,37,0.0,0,1346.6,384,0,0,428.1,47,10.0,1,54.00,3,295.0,19,192,17,24,2,0.0,0,0,0,180.0,55,0.0,0,1481.20,410,0,0,390.5,41,20.0,2,90.0,5,425.0,26,148,14,8,1,0.0,0,0,0,130.0,32,0.0,0,1632.8,438,0.0,0,1095,79,39.0,4,90.0,5,352.00,28,94,9,8,1,0,0,0,0,131.0,44,47.5,21,1190.3,341,0,0,569,55,40.0,4,0.0,0,424.0,31,190,19,8,1,0,0,0,0,122.0,40,40.0,14,940.3,271,414,38,0.0,0,0.0,0,116.00,10,110,12,56.0,3,0,0,0,0,59.0,19,20.5,13,592.8,177,0,0,24,4,0.0,0,0.00,0,84,7,15,2,0.0,0,0,0,0,0,37.0,13,26.5,9,506.4,142,0,0,37,4,0.0,0,0.0,0,32,3,16,1,4.0,1,0,0
1,Ibis budget Strasbourg Centre République,Strasbourg,48.585058,7.736591,0,0,80.0,17,126.0,40,417.0,108,0.0,0,0,0,0.0,0,0.00,0,0,0,0,0,0,0,0.0,0,0,0,85.0,16,193.5,28,466.5,85,0,0,0,0,0.0,0,0.00,0,0,0,0,0,0.0,0,0.0,0,0,0,152.0,18,312.5,64,435.5,120,0,0,0,0,0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,202.5,22,231.0,50,644.5,149,0,0,0.0,0,0.0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,45.0,11,123.0,31,486.0,124,0,0,0,0,0.0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,163.5,33,235.5,74,1310.0,251,0,0,0.0,0,0.0,0,0.00,0,0.0,0,0,0,0,0,0.0,0,0,0,210.5,28,297.0,62,893.00,191,0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0.0,0,0,0,205.5,34,222.5,61,1295.5,291,0.0,0,0,0,0.0,0,0.0,0,0.00,0,0,0,0,0,0,0,0,0,80.0,14,127.5,39,428.5,124,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0,0,0,0,0,207.5,37,336.5,78,997.5,239,0,0,0.0,0,0.0,0,0.00,0,0,0,0.0,0,0,0,0,0,450.0,57,556.0,136,1111.5,275,0,0,0,0,0.0,0,0.00,0,0,0,0,0,0.0,0,0,0,0,0,277.5,66,712.0,173,2374.5,502,0,0,0,0,0.0,0,0.0,0,0,0,0,0,0.0,0,0,0
2,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,1269,62,274.0,46,621.0,71,2630.0,220,29.0,2,0,0,72.5,7,0.00,0,0,0,0,0,38,3,0.0,0,1718,85,552.0,86,441.0,93,3561.5,389,29,2,0,0,350.0,9,0.00,0,0,0,0,0,141.0,8,210.0,2,1765,120,519.0,77,764.0,154,4935.0,542,14,1,0,0,238,11,0.00,0,0,0,0,0,182,10,44,2,2895,160,448.0,92,763.0,127,4983.0,536,168,4,0.0,0,404.0,15,0.00,0,0,0,0,0,96,6,224,4,2055,111,543.0,84,529.0,106,4435.0,397,0,0,0,0,199.0,9,0.0,0,0,0,0,0,124,10,32,1,1135,76,486.0,83,783.0,171,6244.0,590,45,3,0.0,0,266.0,8,0.00,0,0.0,0,0,0,98,4,42.0,1,1569,88,588.0,76,713.0,136,3540.00,341,15,1,0.0,0,55.0,3,0.0,0,0.0,0,0,0,34,3,66.0,3,1646,90,428.0,70,753.0,110,3853.0,278,0.0,0,0,0,12.0,1,0.0,0,0.00,0,0,0,76,5,84,2,3681,180,798.0,131,990.0,160,5911.0,522,0,0,0,0,30.0,1,0.0,0,0.0,0,0,0,42,4,84,2,4091,196,894.0,131,818.0,141,7595.0,648,0,0,70.7,4,0.0,0,0.00,0,0,0,110.8,6,5,1,2450,118,741.0,88,770.0,136,4705.0,419,15,1,0,0,80.7,7,0.00,0,0,0,0,0,65.8,5,0,0,2821,116,558.0,91,809.0,106,4305.0,414,0,0,0,0,228.4,17,0.0,0,0,0,0,0,62.9,5,22,1
3,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,16,1,78.0,6,544.9,41,108.0,27,16.5,1,183,8,0.0,0,248.05,12,120,6,591,22,112,6,1.5,2,40,2,79.7,10,385.8,65,204.0,45,0,0,372,16,51.9,6,349.25,25,33,3,340,11,545.5,27,7.5,6,0,0,152.0,15,289.5,51,94.5,22,0,0,213,9,137,9,486.75,36,60,5,480,13,89,10,23,6,0,0,63.0,11,290.0,30,62.0,19,0,0,302.0,12,279.5,13,250.15,18,33,3,105,3,123,7,130,4,60,4,75.0,11,210.4,25,114.0,32,14,1,415,11,476.8,16,198.4,13,60,4,205,5,116,5,32,1,112,7,114.0,17,312.5,33,120.0,33,7,1,421.0,14,269.8,13,318.05,20,196.5,13,100,3,180,12,6.5,3,52,4,192.5,37,513.0,76,250.00,65,6,1,387.0,13,263.9,17,320.7,20,354.5,22,309,9,376,25,112.0,3,32,3,229.7,39,595.6,80,338.5,84,36.7,3,514,17,122.4,10,615.1,42,917.95,50,637,20,535,39,70,4,52,4,61.0,12,213.3,33,163.0,41,33,2,788,16,221.6,15,230.8,18,389.5,25,302,8,236,18,86,6,140,11,78.0,8,148.8,16,75.0,20,240,5,163.4,9,110.2,8,71.95,5,70,3,55.0,4,96,6,16,2,117.3,22,205.6,19,99.0,24,0,0,797,16,276.9,11,119.85,9,139,13,225,6,335.0,28,21,5,8,1,162.0,33,792.3,126,312.5,88,133,6,535,17,129.4,12,403.9,28,195,19,660,21,456.0,31,101,7
4,Novotel Paris Tour Eiffel,Paris,48.849660,2.283704,0,0,2835.1,311,1712.8,286,3864.5,608,0.0,0,0,0,0.0,0,0.00,0,0,0,0,0,2419,238,0.0,0,0,0,2883.1,309,1810.0,294,4201.3,649,0,0,0,0,24.0,3,0.00,0,0,0,0,0,3432.0,351,0.0,0,0,0,3580.5,342,2105.3,342,4495.8,748,0,0,0,0,48,5,0.00,0,0,0,0,0,3052,344,0,0,0,0,4798.5,457,2277.1,370,5319.3,916,0,0,0.0,0,16.0,2,0.00,0,0,0,0,0,2322,256,0,0,0,0,4658.0,487,2031.7,359,5888.8,971,0,0,0,0,48.0,6,0.0,0,0,0,0,0,2648,280,0,0,0,0,5002.9,559,2407.5,381,9538.6,1194,0,0,0.0,0,24.0,3,0.00,0,0.0,0,0,0,3962,355,0.0,0,0,0,6773.5,657,3154.5,461,11696.67,1442,0,0,0.0,0,48.0,6,0.0,0,0.0,0,0,0,4101,350,18.5,1,0,0,4618.7,484,2161.4,326,7344.1,1074,0.0,0,0,0,56.0,7,0.0,0,0.00,0,0,0,3497,332,0,0,0,0,3710.7,438,1838.4,314,6094.3,994,0,0,0,0,40.0,5,0.0,0,0.0,0,0,0,3801,370,0,0,0,0,6031.9,730,3906.2,680,10381.2,1638,0,0,80.0,8,0.0,0,0.00,0,0,0,7104.0,696,0,0,0,0,5742.6,677,3142.9,548,8543.9,1396,0,0,0,0,32.0,3,0.00,0,0,0,0,0,6268.0,640,0,0,0,0,7239.4,732,4044.9,688,11043.1,1755,0,0,0,0,120.0,12,0.0,0,0,0,0,0,5662.0,594,0,0

In [93]:
poi_weather_df.head(3)

                                 HOTEL_NAME  HOTEL_LAT  HOTEL_LON  fb_0_1km  \
0                          Ibis budget Nice   43.66757    7.21431         0
1  Ibis budget Strasbourg Centre République   48.58506    7.73659         0
2       Mercure Paris Montmartre Sacré-Cœur   48.88524    2.33006         6

   fb_0_2km  fb_0_3km  fb_0_4km  fb_0_5km  not_fb_0_1km  not_fb_0_2km  \
0         0         0         3         3             3             3
1        30        60       102       120             0             3
2        12        57       123       195             3             3

   not_fb_0_3km  not_fb_0_4km  not_fb_0_5km  m01_dwpt_max  m01_dwpt_max.1  \
0             6             6             6          11.7            13.8
1             3            24            36          10.9            10.1
2            27            45            54          12.0            10.2

   m01_dwpt_max.2  m01_dwpt_max.3  m01_dwpt_max.4  m01_dwpt_max.5  \
0            10.1            11.7            13.8            10.1
1             8.1            10.9            10.1             8.1
2             8.9            12.0            10.2             8.9

   m01_dwpt_max.6  m01_dwpt_max.7  m01_dwpt_max.8  m01_dwpt_mean  \
0            11.7            13.8            10.1       4.190188
1            10.9            10.1             8.1       0.284812
2            12.0            10.2             8.9       1.649194

   m01_dwpt_mean.1  m01_dwpt_mean.2  m01_dwpt_mean.3  m01_dwpt_mean.4  \
0         4.944220         2.316801         4.190188         4.944220
1         0.931855        -0.064382         0.284812         0.931855
2         2.165860         2.820565         1.649194         2.165860

   m01_dwpt_mean.5  m01_dwpt_mean.6  m01_dwpt_mean.7  m01_dwpt_mean.8  \
0         2.316801         4.190188         4.944220         2.316801
1        -0.064382         0.284812         0.931855        -0.064382
2         2.820565         1.649194         2.165860         2.820565

   m01_dwpt_median  m01_dwpt_median.1  m01_dwpt_median.2  m01_dwpt_median.3  \
0             4.85                6.0                3.1               4.85
1             0.00                0.1                0.0               0.00
2             0.95                1.9                3.5               0.95

   m01_dwpt_median.4  m01_dwpt_median.5  m01_dwpt_median.6  m01_dwpt_median.7  \
0                6.0                3.1               4.85                6.0
1                0.1                0.0               0.00                0.1
2                1.9                3.5               0.95                1.9

   m01_dwpt_median.8  m01_dwpt_min  m01_dwpt_min.1  m01_dwpt_min.2  \
0                3.1          -7.7            -7.8           -11.7
1                0.0          -9.8            -6.0           -11.1
2                3.5          -7.9            -5.2            -6.5

   m01_dwpt_min.3  m01_dwpt_min.4  m01_dwpt_min.5  m01_dwpt_min.6  \
0            -7.7            -7.8           -11.7            -7.7
1            -9.8            -6.0           -11.1            -9.8
2            -7.9            -5.2            -6.5            -7.9

   m01_dwpt_min.7  m01_dwpt_min.8  m01_dwpt_q25  m01_dwpt_q25.1  \
0            -7.8           -11.7           2.1             2.7
1            -6.0           -11.1          -4.3            -1.4
2            -5.2            -6.5          -3.2            -0.6

   m01_dwpt_q25.2  m01_dwpt_q25.3  m01_dwpt_q25.4  m01_dwpt_q25.5  \
0            -0.9             2.1             2.7            -0.9
1            -2.0            -4.3            -1.4            -2.0
2             0.2            -3.2            -0.6             0.2

   m01_dwpt_q25.6  m01_dwpt_q25.7  m01_dwpt_q25.8  m01_dwpt_q75  \
0             2.1             2.7            -0.9         6.900
1            -4.3            -1.4            -2.0         4.825
2            -3.2            -0.6             0.2         6.300

   m01_dwpt_q75.1  m01_dwpt_q75.2  m01_dwpt_q75.3  m01_dwpt_q75.4  \
0           8.000             6.0           6.900           8.000
1           3.100             3.0           4.825           3.100
2           4.725             5.8           6.300           4.725

   m01_dwpt_q75.5  m01_dwpt_q75.6  m01_dwpt_q75.7  m01_dwpt_q75.8  m01_index  \
0             6.0           6.900           8.000             6.0          5
1             3.0           4.825           3.100             3.0         71
2             5.8           6.300           4.725             5.8        137

   m01_index.1  m01_index.2  m01_index.3  m01_index.4  m01_index.5  \
0           17           29            5           17           29
1           83           95           71           83           95
2          149          161          137          149          161

   m01_index.6  m01_index.7  m01_index.8  m01_prcp_max  m01_prcp_max.1  \
0            5           17           29           8.0            24.9
1           71           83           95           2.6             3.0
2          137          149          161           2.0             4.4

   m01_prcp_max.2  m01_prcp_max.3  m01_prcp_max.4  m01_prcp_max.5  \
0             5.2             8.0            24.9             5.2
1             2.2             2.6             3.0             2.2
2             3.2             2.0             4.4             3.2

   m01_prcp_max.6  m01_prcp_max.7  m01_prcp_max.8  m01_prcp_mean  \
0             8.0            24.9             5.2       0.091263
1             2.6             3.0             2.2       0.059274
2             2.0             4.4             3.2       0.082392

   m01_prcp_mean.1  m01_prcp_mean.2  m01_prcp_mean.3  m01_prcp_mean.4  \
0         0.201344         0.126075         0.091263         0.201344
1         0.099462         0.075806         0.059274         0.099462
2         0.145565         0.063710         0.082392         0.145565

   m01_prcp_mean.5  m01_prcp_mean.6  m01_prcp_mean.7  m01_prcp_mean.8  \
0         0.126075         0.091263         0.201344         0.126075
1         0.075806         0.059274         0.099462         0.075806
2         0.063710         0.082392         0.145565         0.063710

   m01_prcp_median  m01_prcp_median.1  m01_prcp_median.2  m01_prcp_median.3  \
0                0                  0                  0                  0
1                0                  0                  0                  0
2                0                  0                  0                  0

   m01_prcp_median.4  m01_prcp_median.5  m01_prcp_median.6  m01_prcp_median.7  \
0                  0                  0                  0                  0
1                  0                  0                  0                  0
2                  0                  0                  0                  0

   m01_prcp_median.8  m01_prcp_min  m01_prcp_min.1  m01_prcp_min.2  \
0                  0             0               0               0
1                  0             0               0               0
2                  0             0               0               0

   m01_prcp_min.3  m01_prcp_min.4  m01_prcp_min.5  m01_prcp_min.6  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_min.7  m01_prcp_min.8  m01_prcp_q25  m01_prcp_q25.1  \
0               0               0             0               0
1               0               0             0               0
2               0               0             0               0

   m01_prcp_q25.2  m01_prcp_q25.3  m01_prcp_q25.4  m01_prcp_q25.5  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_q25.6  m01_prcp_q25.7  m01_prcp_q25.8  m01_prcp_q75  \
0               0               0               0             0
1               0               0               0             0
2               0               0               0             0

   m01_prcp_q75.1  m01_prcp_q75.2  m01_prcp_q75.3  m01_prcp_q75.4  \
0             0.0               0               0             0.0
1             0.0               0               0             0.0
2             0.0               0               0             0.0

   m01_prcp_q75.5  m01_prcp_q75.6  m01_prcp_q75.7  m01_prcp_q75.8  \
0               0               0             0.0               0
1               0               0             0.0               0
2               0               0             0.0               0

   m01_pres_max  m01_pres_max.1  m01_pres_max.2  m01_pres_max.3  \
0        1035.9          1032.4          1023.4          1035.9
1        1039.0          1041.9          1027.5          1039.0
2        1037.6          1043.0          1024.6          1037.6

   m01_pres_max.4  m01_pres_max.5  m01_pres_max.6  m01_pres_max.7  \
0          1032.4          1023.4          1035.9          1032.4
1          1041.9          1027.5          1039.0          1041.9
2          1043.0          1024.6          1037.6          1043.0

   m01_pres_max.8  m01_pres_mean  m01_pres_mean.1  m01_pres_mean.2  \
0          1023.4    1018.031317      1017.613306      1007.990323
1          1027.5    1021.235081      1018.150806      1009.160349
2          1024.6    1020.317070      1016.565054      1006.609409

   m01_pres_mean.3  m01_pres_mean.4  m01_pres_mean.5  m01_pres_mean.6  \
0      1018.031317      1017.613306      1007.990323      1018.031317
1      1021.235081      1018.150806      1009.160349      1021.235081
2      1020.317070      1016.565054      1006.609409      1020.317070

   m01_pres_mean.7  m01_pres_mean.8  m01_pres_median  m01_pres_median.1  \
0      1017.613306      1007.990323          1020.05            1017.85
1      1018.150806      1009.160349          1027.00            1019.00
2      1016.565054      1006.609409          1025.65            1017.85

   m01_pres_median.2  m01_pres_median.3  m01_pres_median.4  m01_pres_median.5  \
0             1006.0            1020.05            1017.85             1006.0
1             1011.0            1027.00            1019.00             1011.0
2             1009.6            1025.65            1017.85             1009.6

   m01_pres_median.6  m01_pres_median.7  m01_pres_median.8  m01_pres_min  \
0            1020.05            1017.85             1006.0         996.1
1            1027.00            1019.00             1011.0         987.4
2            1025.65            1017.85             1009.6         984.5

   m01_pres_min.1  m01_pres_min.2  m01_pres_min.3  m01_pres_min.4  \
0           998.0           989.0           996.1           998.0
1           993.7           991.0           987.4           993.7
2           984.9           988.9           984.5           984.9

   m01_pres_min.5  m01_pres_min.6  m01_pres_min.7  m01_pres_min.8  \
0           989.0           996.1           998.0           989.0
1           991.0           987.4           993.7           991.0
2           988.9           984.5           984.9           988.9

   m01_pres_q25  m01_pres_q25.1  m01_pres_q25.2  m01_pres_q25.3  \
0      1008.200          1013.0        1000.000        1008.200
1      1010.975          1008.0        1000.300        1010.975
2      1011.000          1005.1         997.175        1011.000

   m01_pres_q25.4  m01_pres_q25.5  m01_pres_q25.6  m01_pres_q25.7  \
0          1013.0        1000.000        1008.200          1013.0
1          1008.0        1000.300        1010.975          1008.0
2          1005.1         997.175        1011.000          1005.1

   m01_pres_q25.8  m01_pres_q75  m01_pres_q75.1  m01_pres_q75.2  \
0        1000.000        1028.8          1022.0        1017.000
1        1000.300        1031.6          1029.0        1016.900
2         997.175        1029.4          1028.5        1014.325

   m01_pres_q75.3  m01_pres_q75.4  m01_pres_q75.5  m01_pres_q75.6  \
0          1028.8          1022.0        1017.000          1028.8
1          1031.6          1029.0        1016.900          1031.6
2          1029.4          1028.5        1014.325          1029.4

   m01_pres_q75.7  m01_pres_q75.8  m01_rhum_max  m01_rhum_max.1  \
0          1022.0        1017.000            96             100
1          1029.0        1016.900           100             100
2          1028.5        1014.325            97             100

   m01_rhum_max.2  m01_rhum_max.3  m01_rhum_max.4  m01_rhum_max.5  \
0             100              96             100             100
1             100             100             100             100
2             100              97             100             100

   m01_rhum_max.6  m01_rhum_max.7  m01_rhum_max.8  m01_rhum_mean  \
0              96             100             100      68.086022
1             100             100             100      83.168011
2              97             100             100      79.572581

   m01_rhum_mean.1  m01_rhum_mean.2  m01_rhum_mean.3  m01_rhum_mean.4  \
0        69.806452        63.106183        68.086022        69.806452
1        84.180108        88.721774        83.168011        84.180108
2        86.268817        86.686828        79.572581        86.268817

   m01_rhum_mean.5  m01_rhum_mean.6  m01_rhum_mean.7  m01_rhum_mean.8  \
0        63.106183        68.086022        69.806452        63.106183
1        88.721774        83.168011        84.180108        88.721774
2        86.686828        79.572581        86.268817        86.686828

   m01_rhum_median  m01_rhum_median.1  m01_rhum_median.2  m01_rhum_median.3  \
0               69               69.5                 62                 69
1               85               87.0                 92                 85
2               81               87.5                 88                 81

   m01_rhum_median.4  m01_rhum_median.5  m01_rhum_median.6  m01_rhum_median.7  \
0               69.5                 62                 69               69.5
1               87.0                 92                 85               87.0
2               87.5                 88                 81               87.5

   m01_rhum_median.8  m01_rhum_min  m01_rhum_min.1  m01_rhum_min.2  \
0                 62            24              28              17
1                 92            54              46              56
2                 88            41              59              59

   m01_rhum_min.3  m01_rhum_min.4  m01_rhum_min.5  m01_rhum_min.6  \
0              24              28              17              24
1              54              46              56              54
2              41              59              59              41

   m01_rhum_min.7  m01_rhum_min.8  m01_rhum_q25  m01_rhum_q25.1  \
0              28              17          61.0           58.75
1              46              56          74.0           76.00
2              59              59          73.0           80.00

   m01_rhum_q25.2  m01_rhum_q25.3  m01_rhum_q25.4  m01_rhum_q25.5  \
0              53            61.0           58.75              53
1              83            74.0           76.00              83
2              81            73.0           80.00              81

   m01_rhum_q25.6  m01_rhum_q25.7  m01_rhum_q25.8  m01_rhum_q75  \
0            61.0           58.75              53            78
1            74.0           76.00              83            92
2            73.0           80.00              81            88

   m01_rhum_q75.1  m01_rhum_q75.2  m01_rhum_q75.3  m01_rhum_q75.4  \
0           83.00              76              78           83.00
1           94.25              96              92           94.25
2           94.00              93              88           94.00

   m01_rhum_q75.5  m01_rhum_q75.6  m01_rhum_q75.7  m01_rhum_q75.8  \
0              76              78           83.00              76
1              96              92           94.25              96
2              93              88           94.00              93

   m01_snow_max  m01_snow_max.1  m01_snow_max.2  m01_snow_max.3  \
0           0.0             0.0             0.0             0.0
1           0.0             4.0             2.0             0.0
2           2.0             0.0             7.0             2.0

   m01_snow_max.4  m01_snow_max.5  m01_snow_max.6  m01_snow_max.7  \
0             0.0             0.0             0.0             0.0
1             4.0             2.0             0.0             4.0
2             0.0             7.0             2.0             0.0

   m01_snow_max.8  m01_snow_mean  m01_snow_mean.1  m01_snow_mean.2  \
0             0.0        0.00000         0.000000         0.000000
1             2.0        0.00000         0.028226         0.052419
2             7.0        0.08871         0.000000         0.477734

   m01_snow_mean.3  m01_snow_mean.4  m01_snow_mean.5  m01_snow_mean.6  \
0          0.00000         0.000000         0.000000          0.00000
1          0.00000         0.028226         0.052419          0.00000
2          0.08871         0.000000         0.477734          0.08871

   m01_snow_mean.7  m01_snow_mean.8  m01_snow_median  m01_snow_median.1  \
0         0.000000         0.000000              0.0                0.0
1         0.028226         0.052419              0.0                0.0
2         0.000000         0.477734              0.0                0.0

   m01_snow_median.2  m01_snow_median.3  m01_snow_median.4  m01_snow_median.5  \
0                0.0                0.0                0.0                0.0
1                0.0                0.0                0.0                0.0
2                0.0                0.0                0.0                0.0

   m01_snow_median.6  m01_snow_median.7  m01_snow_median.8  m01_snow_min  \
0                0.0                0.0                0.0           0.0
1                0.0                0.0                0.0           0.0
2                0.0                0.0                0.0           0.0

   m01_snow_min.1  m01_snow_min.2  m01_snow_min.3  m01_snow_min.4  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_min.5  m01_snow_min.6  m01_snow_min.7  m01_snow_min.8  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_q25  m01_snow_q25.1  m01_snow_q25.2  m01_snow_q25.3  \
0           0.0             0.0             0.0             0.0
1           0.0             0.0             0.0             0.0
2           0.0             0.0             0.0             0.0

   m01_snow_q25.4  m01_snow_q25.5  m01_snow_q25.6  m01_snow_q25.7  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_q25.8  m01_snow_q75  m01_snow_q75.1  m01_snow_q75.2  \
0             0.0           0.0             0.0             0.0
1             0.0           0.0             0.0             0.0
2             0.0           0.0             0.0             0.0

   m01_snow_q75.3  m01_snow_q75.4  m01_snow_q75.5  m01_snow_q75.6  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_q75.7  m01_snow_q75.8  m01_temp_max  m01_temp_max.1  \
0             0.0             0.0          19.6            18.9
1             0.0             0.0          14.5            17.0
2             0.0             0.0          14.4            12.8


In [100]:
# Arrondi des coordonnées
poi_df["HOTEL_LAT"] = poi_df["HOTEL_LAT"].round(5)
poi_df["HOTEL_LON"] = poi_df["HOTEL_LON"].round(5)

weather_df["HOTEL_LAT"] = weather_df["HOTEL_LAT"].round(5)
weather_df["HOTEL_LON"] = weather_df["HOTEL_LON"].round(5)

transaction_df["HOTEL_LAT"] = transaction_df["HOTEL_LAT"].round(5)
transaction_df["HOTEL_LON"] = transaction_df["HOTEL_LON"].round(5)



# =========================
# Merge POI + WEATHER
# =========================
poi_weather_df = poi_df.merge(
    weather_df,
    on=["HOTEL_LAT", "HOTEL_LON"],
    how="inner"
)

poi_weather_df = poi_weather_df.drop(["HOTEL_LAT", "HOTEL_LON"], axis = 1)

# df_final = poi_df.merge(
#     weather_df,
#     on=["HOTEL_LAT", "HOTEL_LON"],
#     how="inner"
# )



# =========================
# Merge avec SALES
# =========================

# df_final = poi_weather_df.merge(
#     transaction_df,
#     on=["HOTEL_NAME", "HOTEL_LAT", "HOTEL_LON"],
#     how="inner"
# )

poi_weather_transaction_df = poi_weather_df.merge(
    transaction_df,
    on=["HOTEL_NAME"],
    how="inner"
)

# =========================
# Merge avec ROD
# =========================
# df_final = poi_weather_transaction_df.merge(
#     rod_df,
#     on=["HOTEL_NAME"],
#     how="inner"
# )

poi_weather_transaction_rod_df = poi_weather_transaction_df.merge(
    rod_df,
    on=["HOTEL_NAME"],
    how="inner"
)

merged_df = poi_weather_transaction_rod_df
merged_df = merged_df.fillna(0)

In [101]:
merged_df.head(3)

                                 HOTEL_NAME  fb_0_1km  fb_0_2km  fb_0_3km  \
0                          Ibis budget Nice         0         0         0
1  Ibis budget Strasbourg Centre République         0        30        60
2       Mercure Paris Montmartre Sacré-Cœur         6        12        57

   fb_0_4km  fb_0_5km  not_fb_0_1km  not_fb_0_2km  not_fb_0_3km  not_fb_0_4km  \
0         3         3             3             3             6             6
1       102       120             0             3             3            24
2       123       195             3             3            27            45

   not_fb_0_5km  m01_dwpt_max  m01_dwpt_max.1  m01_dwpt_max.2  m01_dwpt_max.3  \
0             6          11.7            13.8            10.1            11.7
1            36          10.9            10.1             8.1            10.9
2            54          12.0            10.2             8.9            12.0

   m01_dwpt_max.4  m01_dwpt_max.5  m01_dwpt_max.6  m01_dwpt_max.7  \
0            13.8            10.1            11.7            13.8
1            10.1             8.1            10.9            10.1
2            10.2             8.9            12.0            10.2

   m01_dwpt_max.8  m01_dwpt_mean  m01_dwpt_mean.1  m01_dwpt_mean.2  \
0            10.1       4.190188         4.944220         2.316801
1             8.1       0.284812         0.931855        -0.064382
2             8.9       1.649194         2.165860         2.820565

   m01_dwpt_mean.3  m01_dwpt_mean.4  m01_dwpt_mean.5  m01_dwpt_mean.6  \
0         4.190188         4.944220         2.316801         4.190188
1         0.284812         0.931855        -0.064382         0.284812
2         1.649194         2.165860         2.820565         1.649194

   m01_dwpt_mean.7  m01_dwpt_mean.8  m01_dwpt_median  m01_dwpt_median.1  \
0         4.944220         2.316801             4.85                6.0
1         0.931855        -0.064382             0.00                0.1
2         2.165860         2.820565             0.95                1.9

   m01_dwpt_median.2  m01_dwpt_median.3  m01_dwpt_median.4  m01_dwpt_median.5  \
0                3.1               4.85                6.0                3.1
1                0.0               0.00                0.1                0.0
2                3.5               0.95                1.9                3.5

   m01_dwpt_median.6  m01_dwpt_median.7  m01_dwpt_median.8  m01_dwpt_min  \
0               4.85                6.0                3.1          -7.7
1               0.00                0.1                0.0          -9.8
2               0.95                1.9                3.5          -7.9

   m01_dwpt_min.1  m01_dwpt_min.2  m01_dwpt_min.3  m01_dwpt_min.4  \
0            -7.8           -11.7            -7.7            -7.8
1            -6.0           -11.1            -9.8            -6.0
2            -5.2            -6.5            -7.9            -5.2

   m01_dwpt_min.5  m01_dwpt_min.6  m01_dwpt_min.7  m01_dwpt_min.8  \
0           -11.7            -7.7            -7.8           -11.7
1           -11.1            -9.8            -6.0           -11.1
2            -6.5            -7.9            -5.2            -6.5

   m01_dwpt_q25  m01_dwpt_q25.1  m01_dwpt_q25.2  m01_dwpt_q25.3  \
0           2.1             2.7            -0.9             2.1
1          -4.3            -1.4            -2.0            -4.3
2          -3.2            -0.6             0.2            -3.2

   m01_dwpt_q25.4  m01_dwpt_q25.5  m01_dwpt_q25.6  m01_dwpt_q25.7  \
0             2.7            -0.9             2.1             2.7
1            -1.4            -2.0            -4.3            -1.4
2            -0.6             0.2            -3.2            -0.6

   m01_dwpt_q25.8  m01_dwpt_q75  m01_dwpt_q75.1  m01_dwpt_q75.2  \
0            -0.9         6.900           8.000             6.0
1            -2.0         4.825           3.100             3.0
2             0.2         6.300           4.725             5.8

   m01_dwpt_q75.3  m01_dwpt_q75.4  m01_dwpt_q75.5  m01_dwpt_q75.6  \
0           6.900           8.000             6.0           6.900
1           4.825           3.100             3.0           4.825
2           6.300           4.725             5.8           6.300

   m01_dwpt_q75.7  m01_dwpt_q75.8  m01_index  m01_index.1  m01_index.2  \
0           8.000             6.0          5           17           29
1           3.100             3.0         71           83           95
2           4.725             5.8        137          149          161

   m01_index.3  m01_index.4  m01_index.5  m01_index.6  m01_index.7  \
0            5           17           29            5           17
1           71           83           95           71           83
2          137          149          161          137          149

   m01_index.8  m01_prcp_max  m01_prcp_max.1  m01_prcp_max.2  m01_prcp_max.3  \
0           29           8.0            24.9             5.2             8.0
1           95           2.6             3.0             2.2             2.6
2          161           2.0             4.4             3.2             2.0

   m01_prcp_max.4  m01_prcp_max.5  m01_prcp_max.6  m01_prcp_max.7  \
0            24.9             5.2             8.0            24.9
1             3.0             2.2             2.6             3.0
2             4.4             3.2             2.0             4.4

   m01_prcp_max.8  m01_prcp_mean  m01_prcp_mean.1  m01_prcp_mean.2  \
0             5.2       0.091263         0.201344         0.126075
1             2.2       0.059274         0.099462         0.075806
2             3.2       0.082392         0.145565         0.063710

   m01_prcp_mean.3  m01_prcp_mean.4  m01_prcp_mean.5  m01_prcp_mean.6  \
0         0.091263         0.201344         0.126075         0.091263
1         0.059274         0.099462         0.075806         0.059274
2         0.082392         0.145565         0.063710         0.082392

   m01_prcp_mean.7  m01_prcp_mean.8  m01_prcp_median  m01_prcp_median.1  \
0         0.201344         0.126075                0                  0
1         0.099462         0.075806                0                  0
2         0.145565         0.063710                0                  0

   m01_prcp_median.2  m01_prcp_median.3  m01_prcp_median.4  m01_prcp_median.5  \
0                  0                  0                  0                  0
1                  0                  0                  0                  0
2                  0                  0                  0                  0

   m01_prcp_median.6  m01_prcp_median.7  m01_prcp_median.8  m01_prcp_min  \
0                  0                  0                  0             0
1                  0                  0                  0             0
2                  0                  0                  0             0

   m01_prcp_min.1  m01_prcp_min.2  m01_prcp_min.3  m01_prcp_min.4  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_min.5  m01_prcp_min.6  m01_prcp_min.7  m01_prcp_min.8  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_q25  m01_prcp_q25.1  m01_prcp_q25.2  m01_prcp_q25.3  \
0             0               0               0               0
1             0               0               0               0
2             0               0               0               0

   m01_prcp_q25.4  m01_prcp_q25.5  m01_prcp_q25.6  m01_prcp_q25.7  \
0               0               0               0               0
1               0               0               0               0
2               0               0               0               0

   m01_prcp_q25.8  m01_prcp_q75  m01_prcp_q75.1  m01_prcp_q75.2  \
0               0             0             0.0               0
1               0             0             0.0               0
2               0             0             0.0               0

   m01_prcp_q75.3  m01_prcp_q75.4  m01_prcp_q75.5  m01_prcp_q75.6  \
0               0             0.0               0               0
1               0             0.0               0               0
2               0             0.0               0               0

   m01_prcp_q75.7  m01_prcp_q75.8  m01_pres_max  m01_pres_max.1  \
0             0.0               0        1035.9          1032.4
1             0.0               0        1039.0          1041.9
2             0.0               0        1037.6          1043.0

   m01_pres_max.2  m01_pres_max.3  m01_pres_max.4  m01_pres_max.5  \
0          1023.4          1035.9          1032.4          1023.4
1          1027.5          1039.0          1041.9          1027.5
2          1024.6          1037.6          1043.0          1024.6

   m01_pres_max.6  m01_pres_max.7  m01_pres_max.8  m01_pres_mean  \
0          1035.9          1032.4          1023.4    1018.031317
1          1039.0          1041.9          1027.5    1021.235081
2          1037.6          1043.0          1024.6    1020.317070

   m01_pres_mean.1  m01_pres_mean.2  m01_pres_mean.3  m01_pres_mean.4  \
0      1017.613306      1007.990323      1018.031317      1017.613306
1      1018.150806      1009.160349      1021.235081      1018.150806
2      1016.565054      1006.609409      1020.317070      1016.565054

   m01_pres_mean.5  m01_pres_mean.6  m01_pres_mean.7  m01_pres_mean.8  \
0      1007.990323      1018.031317      1017.613306      1007.990323
1      1009.160349      1021.235081      1018.150806      1009.160349
2      1006.609409      1020.317070      1016.565054      1006.609409

   m01_pres_median  m01_pres_median.1  m01_pres_median.2  m01_pres_median.3  \
0          1020.05            1017.85             1006.0            1020.05
1          1027.00            1019.00             1011.0            1027.00
2          1025.65            1017.85             1009.6            1025.65

   m01_pres_median.4  m01_pres_median.5  m01_pres_median.6  m01_pres_median.7  \
0            1017.85             1006.0            1020.05            1017.85
1            1019.00             1011.0            1027.00            1019.00
2            1017.85             1009.6            1025.65            1017.85

   m01_pres_median.8  m01_pres_min  m01_pres_min.1  m01_pres_min.2  \
0             1006.0         996.1           998.0           989.0
1             1011.0         987.4           993.7           991.0
2             1009.6         984.5           984.9           988.9

   m01_pres_min.3  m01_pres_min.4  m01_pres_min.5  m01_pres_min.6  \
0           996.1           998.0           989.0           996.1
1           987.4           993.7           991.0           987.4
2           984.5           984.9           988.9           984.5

   m01_pres_min.7  m01_pres_min.8  m01_pres_q25  m01_pres_q25.1  \
0           998.0           989.0      1008.200          1013.0
1           993.7           991.0      1010.975          1008.0
2           984.9           988.9      1011.000          1005.1

   m01_pres_q25.2  m01_pres_q25.3  m01_pres_q25.4  m01_pres_q25.5  \
0        1000.000        1008.200          1013.0        1000.000
1        1000.300        1010.975          1008.0        1000.300
2         997.175        1011.000          1005.1         997.175

   m01_pres_q25.6  m01_pres_q25.7  m01_pres_q25.8  m01_pres_q75  \
0        1008.200          1013.0        1000.000        1028.8
1        1010.975          1008.0        1000.300        1031.6
2        1011.000          1005.1         997.175        1029.4

   m01_pres_q75.1  m01_pres_q75.2  m01_pres_q75.3  m01_pres_q75.4  \
0          1022.0        1017.000          1028.8          1022.0
1          1029.0        1016.900          1031.6          1029.0
2          1028.5        1014.325          1029.4          1028.5

   m01_pres_q75.5  m01_pres_q75.6  m01_pres_q75.7  m01_pres_q75.8  \
0        1017.000          1028.8          1022.0        1017.000
1        1016.900          1031.6          1029.0        1016.900
2        1014.325          1029.4          1028.5        1014.325

   m01_rhum_max  m01_rhum_max.1  m01_rhum_max.2  m01_rhum_max.3  \
0            96             100             100              96
1           100             100             100             100
2            97             100             100              97

   m01_rhum_max.4  m01_rhum_max.5  m01_rhum_max.6  m01_rhum_max.7  \
0             100             100              96             100
1             100             100             100             100
2             100             100              97             100

   m01_rhum_max.8  m01_rhum_mean  m01_rhum_mean.1  m01_rhum_mean.2  \
0             100      68.086022        69.806452        63.106183
1             100      83.168011        84.180108        88.721774
2             100      79.572581        86.268817        86.686828

   m01_rhum_mean.3  m01_rhum_mean.4  m01_rhum_mean.5  m01_rhum_mean.6  \
0        68.086022        69.806452        63.106183        68.086022
1        83.168011        84.180108        88.721774        83.168011
2        79.572581        86.268817        86.686828        79.572581

   m01_rhum_mean.7  m01_rhum_mean.8  m01_rhum_median  m01_rhum_median.1  \
0        69.806452        63.106183               69               69.5
1        84.180108        88.721774               85               87.0
2        86.268817        86.686828               81               87.5

   m01_rhum_median.2  m01_rhum_median.3  m01_rhum_median.4  m01_rhum_median.5  \
0                 62                 69               69.5                 62
1                 92                 85               87.0                 92
2                 88                 81               87.5                 88

   m01_rhum_median.6  m01_rhum_median.7  m01_rhum_median.8  m01_rhum_min  \
0                 69               69.5                 62            24
1                 85               87.0                 92            54
2                 81               87.5                 88            41

   m01_rhum_min.1  m01_rhum_min.2  m01_rhum_min.3  m01_rhum_min.4  \
0              28              17              24              28
1              46              56              54              46
2              59              59              41              59

   m01_rhum_min.5  m01_rhum_min.6  m01_rhum_min.7  m01_rhum_min.8  \
0              17              24              28              17
1              56              54              46              56
2              59              41              59              59

   m01_rhum_q25  m01_rhum_q25.1  m01_rhum_q25.2  m01_rhum_q25.3  \
0          61.0           58.75              53            61.0
1          74.0           76.00              83            74.0
2          73.0           80.00              81            73.0

   m01_rhum_q25.4  m01_rhum_q25.5  m01_rhum_q25.6  m01_rhum_q25.7  \
0           58.75              53            61.0           58.75
1           76.00              83            74.0           76.00
2           80.00              81            73.0           80.00

   m01_rhum_q25.8  m01_rhum_q75  m01_rhum_q75.1  m01_rhum_q75.2  \
0              53            78           83.00              76
1              83            92           94.25              96
2              81            88           94.00              93

   m01_rhum_q75.3  m01_rhum_q75.4  m01_rhum_q75.5  m01_rhum_q75.6  \
0              78           83.00              76              78
1              92           94.25              96              92
2              88           94.00              93              88

   m01_rhum_q75.7  m01_rhum_q75.8  m01_snow_max  m01_snow_max.1  \
0           83.00              76           0.0             0.0
1           94.25              96           0.0             4.0
2           94.00              93           2.0             0.0

   m01_snow_max.2  m01_snow_max.3  m01_snow_max.4  m01_snow_max.5  \
0             0.0             0.0             0.0             0.0
1             2.0             0.0             4.0             2.0
2             7.0             2.0             0.0             7.0

   m01_snow_max.6  m01_snow_max.7  m01_snow_max.8  m01_snow_mean  \
0             0.0             0.0             0.0        0.00000
1             0.0             4.0             2.0        0.00000
2             2.0             0.0             7.0        0.08871

   m01_snow_mean.1  m01_snow_mean.2  m01_snow_mean.3  m01_snow_mean.4  \
0         0.000000         0.000000          0.00000         0.000000
1         0.028226         0.052419          0.00000         0.028226
2         0.000000         0.477734          0.08871         0.000000

   m01_snow_mean.5  m01_snow_mean.6  m01_snow_mean.7  m01_snow_mean.8  \
0         0.000000          0.00000         0.000000         0.000000
1         0.052419          0.00000         0.028226         0.052419
2         0.477734          0.08871         0.000000         0.477734

   m01_snow_median  m01_snow_median.1  m01_snow_median.2  m01_snow_median.3  \
0              0.0                0.0                0.0                0.0
1              0.0                0.0                0.0                0.0
2              0.0                0.0                0.0                0.0

   m01_snow_median.4  m01_snow_median.5  m01_snow_median.6  m01_snow_median.7  \
0                0.0                0.0                0.0                0.0
1                0.0                0.0                0.0                0.0
2                0.0                0.0                0.0                0.0

   m01_snow_median.8  m01_snow_min  m01_snow_min.1  m01_snow_min.2  \
0                0.0           0.0             0.0             0.0
1                0.0           0.0             0.0             0.0
2                0.0           0.0             0.0             0.0

   m01_snow_min.3  m01_snow_min.4  m01_snow_min.5  m01_snow_min.6  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_min.7  m01_snow_min.8  m01_snow_q25  m01_snow_q25.1  \
0             0.0             0.0           0.0             0.0
1             0.0             0.0           0.0             0.0
2             0.0             0.0           0.0             0.0

   m01_snow_q25.2  m01_snow_q25.3  m01_snow_q25.4  m01_snow_q25.5  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_q25.6  m01_snow_q25.7  m01_snow_q25.8  m01_snow_q75  \
0             0.0             0.0             0.0           0.0
1             0.0             0.0             0.0           0.0
2             0.0             0.0             0.0           0.0

   m01_snow_q75.1  m01_snow_q75.2  m01_snow_q75.3  m01_snow_q75.4  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_snow_q75.5  m01_snow_q75.6  m01_snow_q75.7  m01_snow_q75.8  \
0             0.0             0.0             0.0             0.0
1             0.0             0.0             0.0             0.0
2             0.0             0.0             0.0             0.0

   m01_temp_max  m01_temp_max.1  m01_temp_max.2  m01_temp_max.3  \
0          19.6            18.9            16.0            19.6
1          14.5            17.0            14.0            14.5
2          14.4            12.8            12.6            14.4


In [102]:
merged_df.shape

(5, 5457)

In [103]:
merged_df.to_excel("ml_data.xlsx", index = False)