In [1]:
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

import keras
import re

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1782479455.283449   44614 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [63]:
# Chemin vers le fichier Excel
file_path = "selection_rod.xlsx"

# Lecture de la première feuille Excel
# header=None pour garder les lignes telles quelles
df_rod = pd.read_excel(file_path, sheet_name=0, header=None)

# Ligne 1 = indicateurs (1 = garder)
keep_mask = df_rod.iloc[0].fillna(0).astype(str).str.strip() == "1"

# Ligne 2 = noms de colonnes
columns = df_rod.iloc[1]

# Données à partir de la ligne 3
df_rod_clean = df_rod.iloc[2:, keep_mask.values].copy()

# Appliquer les noms de colonnes uniquement sur les colonnes gardées
df_rod_clean.columns = columns[keep_mask].values

# Réinitialiser l'index
df_rod_clean.reset_index(drop=True, inplace=True)

df_rod_clean = df_rod_clean.replace({
    "OUI": 1,
    "X": 1,
    "NON": 0,
    "-": 0,
    " - " : 0,
    "": np.nan,
    #np.nan: 0
})

# Remplacer les "?" par la moyenne de la colonne
for col in df_rod_clean.columns:
    mask_question = df_rod_clean[col].astype(str).str.strip() == "?"

    if mask_question.any():
        serie_numeric = pd.to_numeric(
            df_rod_clean[col].replace("?", np.nan),
            errors="coerce"
        )

        moyenne = serie_numeric.mean()

        df_rod_clean.loc[mask_question, col] = moyenne

# Remplacer les NaN restants par 0
df_rod_clean = df_rod_clean.fillna(0)

# df_marques = pd.get_dummies(df_rod_clean["MARQUE"], dtype = int, prefix="MARQUE", prefix_sep = " ")
# df_rod_clean[df_marques.columns] = df_marques

dummy_columns = ["MARQUE", "PMS"]
df_dummies = pd.get_dummies(df_rod_clean, columns = dummy_columns, dtype = int, prefix_sep = " ")
df_rod_clean[df_dummies.columns] = df_dummies
df_rod_clean = df_rod_clean.drop(dummy_columns, axis = 1)

df_rod_clean.rename(columns={"LATITUDE": "HOTEL_LAT", "LONGITUDE" : "HOTEL_LON", "NOM DE L'HOTEL" : "HOTEL_NAME", "CODE H" : "HOTEL_CODE"}, inplace=True)

/tmp/ipykernel_21865/2665346326.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  keep_mask = df_rod.iloc[0].fillna(0).astype(str).str.strip() == "1"
/tmp/ipykernel_21865/2665346326.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean = df_rod_clean.replace({
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:39: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean[col].replace("?", np.nan),
/tmp/ipykernel_21865/2665346326.py:48: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rod_clean = df_rod_clean.fillna(0)

In [64]:
df_rod_clean

,HOTEL_CODE,HOTEL_NAME,HOTEL_LON,HOTEL_LAT,NB. DE CHAMBRES,CONTRAT SIGNE (ANNEE),DERNIERE RENO HOTEL,DERNIERE RENO LOBBY,TO ANNUEL,TO LE PLUS BAS (TAUX),TO LE PLUS HAUT (TAUX),BAR,RESTAURANT,SALLES DE REUNION,SALLE DE SPORT,PISCINE,VITRINE RÉFRIGÉRÉE,MICRO-ONDES,FONTAINE À EAU,MACHINE À CAFÉ,BOUILLOIRE,LOISIRS (%),TOP 1 > COUPLES,TOP 1 > AMIS,TOP 1 > FAMILLES,AFFAIRES (%),NATIONAL (%),INTERNATIONAL (%),MÈTRES LINÉAIRES DEDIES A VOTRE CORNER (ACTUEL OU FUTUR),MARQUE IBIS BUDGET,MARQUE IBIS STYLES,MARQUE MERCURE,MARQUE NOVOTEL,PMS FOLS,PMS OPERA
0,H2075,IBIS BUDGET NICE CALIFORNIE,7.240512,43.689186,129,2003.666667,2020.0,2020.0,0.825,0.755,0.89,0,0,4,0,0,1,1,1,1,0.166667,70.0,0,1,0,30.0,65.0,35.0,6,1,0,0,0,1,0
1,HB6A3,IBIS BUDGET STRASBOURG REPUBLIQUE,7.754599,48.591522,97,2020.000000,2025.0,2025.0,0.700,0.600,0.80,0,0,0,0,0,0,0,1,1,0.000000,60.0,0,1,0,40.0,60.0,40.0,2,1,0,0,0,0,1
2,H0815,IBIS STYLES ROISSY CDG,2.519843,49.006733,309,2015.000000,2015.0,2015.0,0.950,0.910,0.98,1,1,1,0,0,0,1,1,1,1.000000,80.0,0,0,1,20.0,70.0,30.0,5,0,1,0,0,1,0
3,HB5I0,NOVOTEL MEGEVE MONT BLANC,6.619055,45.859165,572,2003.666667,2020.0,2020.0,0.825,0.755,0.89,1,1,3,2,1,0,0,0,0,0.000000,70.0,0,0,1,30.0,65.0,35.0,8,0,0,0,1,1,0
4,H3546,NOVOTEL PARIS CENTRE TOUR EIFFEL,2.282836,48.849778,764,1976.000000,2020.0,2020.0,0.825,0.755,0.89,1,3,36,1,1,0,0,1,1,0.000000,70.0,0,0,1,30.0,65.0,35.0,7,0,0,0,1,0,1
5,H0373,MERCURE MONTMARTRE SACRE COEUR,2.329923,48.885048,305,2003.666667,2020.0,2020.0,0.825,0.755,0.89,0,1,1,1,0,1,0,0,0,0.000000,70.0,1,0,0,30.0,65.0,35.0,6,0,0,1,0,0,1
6,H6188,MERCURE PARIS BOULOGNE,2.256274,48.833827,191,2003.666667,2020.0,2020.0,0.825,0.755,0.89,1,2,13,1,1,1,0,1,0,0.000000,70.0,1,0,0,30.0,65.0,35.0,6,0,0,1,0,0,1

In [37]:
df_poi = pd.read_csv("poi.csv")

# Types Food & Beverage
fb_types = [
    "convenience", "bakery", "supermarket", "alcohol",
    "confectionery", "beverages", "grocery", "ice_cream"
]

# Types Non Food & Beverage
non_fb_types = [
    "cosmetics", "gift", "tobacco", "kiosk"
]

df_poi["is_fb"] = df_poi["SHOP_TYPE"].isin(fb_types)
df_poi["is_not_fb"] = df_poi["SHOP_TYPE"].isin(non_fb_types)

df_poi_clean = (
    df_poi.groupby(["HOTEL_NAME", "HOTEL_CITY", "HOTEL_LAT", "HOTEL_LON"])
    .apply(lambda x: pd.Series({
        "fb_0_1km": ((x["DIST_KM"] <= 0.1) & x["is_fb"]).sum(),
        "fb_0_2km": ((x["DIST_KM"] <= 0.2) & x["is_fb"]).sum(),
        "fb_0_3km": ((x["DIST_KM"] <= 0.3) & x["is_fb"]).sum(),
        "fb_0_4km": ((x["DIST_KM"] <= 0.4) & x["is_fb"]).sum(),
        "fb_0_5km": ((x["DIST_KM"] <= 0.5) & x["is_fb"]).sum(),
        "not_fb_0_1km": ((x["DIST_KM"] <= 0.1) & x["is_not_fb"]).sum(),
        "not_fb_0_2km": ((x["DIST_KM"] <= 0.2) & x["is_not_fb"]).sum(),
        "not_fb_0_3km": ((x["DIST_KM"] <= 0.3) & x["is_not_fb"]).sum(),
        "not_fb_0_4km": ((x["DIST_KM"] <= 0.4) & x["is_not_fb"]).sum(),
        "not_fb_0_5km": ((x["DIST_KM"] <= 0.5) & x["is_not_fb"]).sum(),
    }))
    .reset_index()
)

/tmp/ipykernel_21865/65113361.py:19: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

In [38]:
df_poi_clean

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,fb_0_1km,fb_0_2km,fb_0_3km,fb_0_4km,fb_0_5km,not_fb_0_1km,not_fb_0_2km,not_fb_0_3km,not_fb_0_4km,not_fb_0_5km
0,Ibis budget Nice,Nice,43.667571,7.214308,0,0,0,3,3,3,3,6,6,6
1,Ibis budget Strasbourg Centre République,Strasbourg,48.585058,7.736591,0,30,60,102,120,0,3,3,24,36
2,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,6,12,57,123,195,3,3,27,45,54
3,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,3,3,6,6,15,0,0,3,3,3
4,Novotel Paris Tour Eiffel,Paris,48.849660,2.283704,3,6,9,36,69,0,9,12,15,18
5,Novotel Porte d’Italie,Paris,48.819054,2.359406,9,18,21,42,75,3,3,3,6,9

In [17]:
df_weather = pd.read_csv("weather.csv")

df_weather["time"] = pd.to_datetime(df_weather["time"])
df_weather["mois"] = df_weather["time"].dt.to_period("M").astype(str)

cols_stats = ["temp", "dwpt", "rhum", "prcp", "snow", "wspd", "wpgt", "pres", "tsun"]

df_weather_clean = (
    df_weather
    .groupby(["lat", "lon", "mois"])[cols_stats]
    .agg([
        "min",
        "max",
        "mean",
        "median",
        lambda x: x.quantile(0.25),
        lambda x: x.quantile(0.75),
    ])
)

df_weather_clean.columns = [
    f"{col}_{stat}"
    for col, stat in df_weather_clean.columns
]

df_weather_clean = df_weather_clean.reset_index()

# Renommer les lambdas
df_weather_clean.columns = (
    df_weather_clean.columns
    .str.replace("<lambda_0>", "q25")
    .str.replace("<lambda_1>", "q75")
)


# Reset index
df_weather_clean = df_weather_clean.reset_index()

# Renommer les lambdas
df_weather_clean.columns = (
    df_weather_clean.columns
    .str.replace("<lambda_0>", "q25")
    .str.replace("<lambda_1>", "q75")
)

# Pivot : une seule ligne par lat/lon
df_weather_clean = df_weather_clean.pivot(
    index=["lat", "lon"],
    columns="mois"
)

# Aplatir les colonnes
df_weather_clean.columns = [
    f"m{pd.to_datetime(month).month:02d}_{col}"
    for col, month in df_weather_clean.columns
]

# Revenir en dataframe classique
df_weather_clean = df_weather_clean.reset_index()

# Trier les colonnes proprement par mois puis nom de feature

ordered_cols = ["lat", "lon"] + sorted(
    [c for c in df_weather_clean.columns if c not in ["lat", "lon"]],
    key=lambda x: (
        int(x.split("_")[0][1:]),  # numéro du mois
        x.split("_", 1)[1]         # reste du nom
    )
)

df_weather_clean = df_weather_clean[ordered_cols]
df_weather_clean.rename(columns={"lat": "HOTEL_LAT", "lon" : "HOTEL_LON"}, inplace=True)

In [18]:
df_weather_clean

   HOTEL_LAT  HOTEL_LON  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  \
0  43.667571   7.214308          11.7          13.8          10.1
1  45.859850   6.619478           7.8           7.3           2.1
2  48.585058   7.736591          10.9          10.1           8.1
3  48.849660   2.283704          12.0          10.2           8.9
4  48.885240   2.330055          12.0          10.2           8.9

   m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  \
0          11.7          13.8          10.1          11.7          13.8
1           7.8           7.3           2.1           7.8           7.3
2          10.9          10.1           8.1          10.9          10.1
3          12.0          10.2           8.9          12.0          10.2
4          12.0          10.2           8.9          12.0          10.2

   m01_dwpt_max  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  \
0          10.1       4.190188       4.944220       2.316801       4.190188
1           2.1      -4.595161      -5.025941      -6.830242      -4.595161
2           8.1       0.284812       0.931855      -0.064382       0.284812
3           8.9       1.649194       2.165860       2.820565       1.649194
4           8.9       1.649194       2.165860       2.820565       1.649194

   m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  \
0       4.944220       2.316801       4.190188       4.944220       2.316801
1      -5.025941      -6.830242      -4.595161      -5.025941      -6.830242
2       0.931855      -0.064382       0.284812       0.931855      -0.064382
3       2.165860       2.820565       1.649194       2.165860       2.820565
4       2.165860       2.820565       1.649194       2.165860       2.820565

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  \
0             4.85              6.0              3.1             4.85
1            -3.00             -3.4             -4.8            -3.00
2             0.00              0.1              0.0             0.00
3             0.95              1.9              3.5             0.95
4             0.95              1.9              3.5             0.95

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  \
0              6.0              3.1             4.85              6.0
1             -3.4             -4.8            -3.00             -3.4
2              0.1              0.0             0.00              0.1
3              1.9              3.5             0.95              1.9
4              1.9              3.5             0.95              1.9

   m01_dwpt_median  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  \
0              3.1          -7.7          -7.8         -11.7          -7.7
1             -4.8         -29.7         -23.9         -27.9         -29.7
2              0.0          -9.8          -6.0         -11.1          -9.8
3              3.5          -7.9          -5.2          -6.5          -7.9
4              3.5          -7.9          -5.2          -6.5          -7.9

   m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  \
0          -7.8         -11.7          -7.7          -7.8         -11.7
1         -23.9         -27.9         -29.7         -23.9         -27.9
2          -6.0         -11.1          -9.8          -6.0         -11.1
3          -5.2          -6.5          -7.9          -5.2          -6.5
4          -5.2          -6.5          -7.9          -5.2          -6.5

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  \
0          2.10           2.7        -0.900          2.10           2.7
1         -7.65          -9.5       -10.325         -7.65          -9.5
2         -4.30          -1.4        -2.000         -4.30          -1.4
3         -3.20          -0.6         0.200         -3.20          -0.6
4         -3.20          -0.6         0.200         -3.20          -0.6

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q75  \
0        -0.900          2.10           2.7        -0.900         6.900
1       -10.325         -7.65          -9.5       -10.325         0.500
2        -2.000         -4.30          -1.4        -2.000         4.825
3         0.200         -3.20          -0.6         0.200         6.300
4         0.200         -3.20          -0.6         0.200         6.300

   m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  \
0         8.000           6.0         6.900         8.000           6.0
1         0.600          -2.0         0.500         0.600          -2.0
2         3.100           3.0         4.825         3.100           3.0
3         4.725           5.8         6.300         4.725           5.8
4         4.725           5.8         6.300         4.725           5.8

   m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_index  m01_index  m01_index  \
0         6.900         8.000           6.0          5         17         29
1         0.500         0.600          -2.0         38         50         62
2         4.825         3.100           3.0         71         83         95
3         6.300         4.725           5.8        104        116        128
4         6.300         4.725           5.8        137        149        161

   m01_index  m01_index  m01_index  m01_index  m01_index  m01_index  \
0          5         17         29          5         17         29
1         38         50         62         38         50         62
2         71         83         95         71         83         95
3        104        116        128        104        116        128
4        137        149        161        137        149        161

   m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  \
0           8.0          24.9           5.2           8.0          24.9
1           4.3           7.9           4.1           4.3           7.9
2           2.6           3.0           2.2           2.6           3.0
3           2.0           4.4           3.2           2.0           4.4
4           2.0           4.4           3.2           2.0           4.4

   m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_mean  \
0           5.2           8.0          24.9           5.2       0.091263
1           4.1           4.3           7.9           4.1       0.229435
2           2.2           2.6           3.0           2.2       0.059274
3           3.2           2.0           4.4           3.2       0.084812
4           3.2           2.0           4.4           3.2       0.082392

   m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  \
0       0.201344       0.126075       0.091263       0.201344       0.126075
1       0.342339       0.183871       0.229435       0.342339       0.183871
2       0.099462       0.075806       0.059274       0.099462       0.075806
3       0.145833       0.063710       0.084812       0.145833       0.063710
4       0.145565       0.063710       0.082392       0.145565       0.063710

   m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_median  \
0       0.091263       0.201344       0.126075              0.0
1       0.229435       0.342339       0.183871              0.0
2       0.059274       0.099462       0.075806              0.0
3       0.084812       0.145833       0.063710              0.0
4       0.082392       0.145565       0.063710              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q75  m01_prcp_q75  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.2
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.2           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_pres_max  m01_pres_max  m01_pres_max  \
0           0.0           0.0        1035.9        1032.4        1023.4
1           0.2           0.0        1038.7        1033.7        1026.2
2           0.0           0.0        1039.0        1041.9        1027.5
3           0.0           0.0        1037.6        1043.0        1024.6
4           0.0           0.0        1037.6        1043.0        1024.6

   m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  \
0        1035.9        1032.4        1023.4        1035.9        1032.4
1        1038.7        1033.7        1026.2        1038.7        1033.7
2        1039.0        1041.9        1027.5        1039.0        1041.9
3        1037.6        1043.0        1024.6        1037.6        1043.0
4        1037.6        1043.0        1024.6        1037.6        1043.0

   m01_pres_max  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  \
0        1023.4    1018.031317    1017.613306    1007.990323    1018.031317
1        1026.2    1020.037097    1018.511290    1010.418683    1020.037097
2        1027.5    1021.235081    1018.150806    1009.160349    1021.235081
3        1024.6    1020.317070    1016.565054    1006.609409    1020.317070
4        1024.6    1020.317070    1016.565054    1006.609409    1020.317070

   m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  \
0    1017.613306    1007.990323    1018.031317    1017.613306    1007.990323
1    1018.511290    1010.418683    1020.037097    1018.511290    1010.418683
2    1018.150806    1009.160349    1021.235081    1018.150806    1009.160349
3    1016.565054    1006.609409    1020.317070    1016.565054    1006.609409
4    1016.565054    1006.609409    1020.317070    1016.565054    1006.609409

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median  \
0          1020.05          1017.85           1006.0          1020.05
1          1020.00          1018.50           1011.9          1020.00
2          1027.00          1019.00           1011.0          1027.00
3          1025.65          1017.85           1009.6          1025.65
4          1025.65          1017.85           1009.6          1025.65

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median  \
0          1017.85           1006.0          1020.05          1017.85
1          1018.50           1011.9          1020.00          1018.50
2          1019.00           1011.0          1027.00          1019.00
3          1017.85           1009.6          1025.65          1017.85
4          1017.85           1009.6          1025.65          1017.85

   m01_pres_median  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  \
0           1006.0         996.1         998.0         989.0         996.1
1           1011.9         993.2         999.7         991.5         993.2
2           1011.0         987.4         993.7         991.0         987.4
3           1009.6         984.5         984.9         988.9         984.5
4           1009.6         984.5         984.9         988.9         984.5

   m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  \
0         998.0         989.0         996.1         998.0         989.0
1         999.7         991.5         993.2         999.7         991.5
2         993.7         991.0         987.4         993.7         991.0
3         984.9         988.9         984.5         984.9         988.9
4         984.9         988.9         984.5         984.9         988.9

   m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  \
0      1008.200        1013.0      1000.000      1008.200        1013.0
1      1011.700        1013.1      1001.300      1011.700        1013.1
2      1010.975        1008.0      1000.300      1010.975        1008.0
3      1011.000        1005.1       997.175      1011.000        1005.1
4      1011.000        1005.1       997.175      1011.000        1005.1

   m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q75  \
0      1000.000      1008.200        1013.0      1000.000        1028.8
1      1001.300      1011.700        1013.1      1001.300        1030.0
2      1000.300      1010.975        1008.0      1000.300        1031.6
3       997.175      1011.000        1005.1       997.175        1029.4
4       997.175      1011.000        1005.1       997.175        1029.4

   m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  \
0        1022.0      1017.000        1028.8        1022.0      1017.000
1        1024.7      1018.200        1030.0        1024.7      1018.200
2        1029.0      1016.900        1031.6        1029.0      1016.900
3        1028.5      1014.325        1029.4        1028.5      1014.325
4        1028.5      1014.325        1029.4        1028.5      1014.325

   m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_rhum_max  m01_rhum_max  \
0        1028.8        1022.0      1017.000          96.0         100.0
1        1030.0        1024.7      1018.200         100.0          99.0
2        1031.6        1029.0      1016.900         100.0         100.0
3        1029.4        1028.5      1014.325          97.0         100.0
4        1029.4        1028.5      1014.325          97.0         100.0

   m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  \
0         100.0          96.0         100.0         100.0          96.0
1          97.0         100.0          99.0          97.0         100.0
2         100.0         100.0         100.0         100.0         100.0
3         100.0          97.0         100.0         100.0          97.0
4         100.0          97.0         100.0         100.0          97.0

   m01_rhum_max  m01_rhum_max  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0         100.0         100.0      68.086022      69.806452      63.106183
1          99.0          97.0      69.505376      70.672043      71.147849
2         100.0         100.0      83.168011      84.180108      88.721774
3         100.0         100.0      79.572581      86.268817      86.686828
4         100.0         100.0      79.572581      86.268817      86.686828

   m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0      68.086022      69.806452      63.106183      68.086022      69.806452
1      69.505376      70.672043      71.147849      69.505376      70.672043
2      83.168011      84.180108      88.721774      83.168011      84.180108
3      79.572581      86.268817      86.686828      79.572581      86.268817
4      79.572581      86.268817      86.686828      79.572581      86.268817

   m01_rhum_mean  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0      63.106183             69.0             69.5             62.0
1      71.147849             84.0             80.0             79.0
2      88.721774             85.0             87.0             92.0
3      86.686828             81.0             87.5             88.0
4      86.686828             81.0             87.5             88.0

   m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0             69.0             69.5             62.0             69.0
1             84.0             80.0             79.0             84.0
2             85.0             87.0             92.0             85.0
3             81.0             87.5             88.0             81.0
4             81.0             87.5             88.0             81.0

   m01_rhum_median  m01_rhum_median  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0             69.5             62.0          24.0          28.0          17.0
1             80.0             79.0           7.0          16.0          20.0
2             87.0             92.0          54.0          46.0          56.0
3             87.5             88.0          41.0          59.0          59.0
4             87.5             88.0          41.0          59.0          59.0

   m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0          24.0          28.0          17.0          24.0          28.0
1           7.0          16.0          20.0           7.0          16.0
2          54.0          46.0          56.0          54.0          46.0
3          41.0          59.0          59.0          41.0          59.0
4          41.0          59.0          59.0          41.0          59.0

   m01_rhum_min  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  \
0          17.0         61.00         58.75          53.0         61.00
1          20.0         45.75         54.00          56.0         45.75
2          56.0         74.00         76.00          83.0         74.00
3          59.0         73.00         80.00          81.0         73.00
4          59.0         73.00         80.00          81.0         73.00

   m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  m01_rhum_q25  \
0         58.75          53.0         61.00         58.75          53.0
1         54.00          56.0         45.75         54.00          56.0
2         76.00          83.0         74.00         76.00          83.0
3         80.00          81.0         73.00         80.00          81.0
4         80.00          81.0         73.00         80.00          81.0

   m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  m01_rhum_q75  \
0          78.0         83.00          76.0          78.0         83.00
1          93.0         90.00          87.0          93.0         90.00
2          92.0         94.25          96.0          92.0         94.25

In [8]:
import pandas as pd

df = pd.read_csv("data.csv")

df["DATETIME"] = pd.to_datetime(df["DATETIME"])
df["mois"] = df["DATETIME"].dt.month

# Montant de vente
df["montant_vente"] = df["PRIX TTC"] * df["QUANTITE"]

# Infos hôtel à garder
hotel_cols = [
    "HOTEL_NAME",
    "HOTEL_CITY",
    "HOTEL_LAT",
    "HOTEL_LON",
]

# Agrégation par hôtel / mois / type
monthly = (
    df
    .groupby(hotel_cols + ["mois", "TYPE"])
    .agg(
        montant=("montant_vente", "sum"),
        nbr_ventes=("ORDER ID (TICKET DE CAISSE)", "nunique")
    )
    .reset_index()
)

# Passage en colonnes
wide = monthly.pivot_table(
    index=hotel_cols,
    columns=["mois", "TYPE"],
    values=["montant", "nbr_ventes"],
    fill_value=0
)

# Aplatir les noms de colonnes
wide.columns = [
    f"m{mois:02d}_{type_}_{metric}"
    .replace("&", "")
    .replace("-", "_")
    .replace(" ", "_")
    for metric, mois, type_ in wide.columns
]

df_hotel_monthly = wide.reset_index()

# Trier les colonnes : infos hôtel puis m01, m02, ...
hotel_cols_final = hotel_cols

monthly_cols = sorted(
    [c for c in df_hotel_monthly.columns if c not in hotel_cols_final],
    key=lambda x: (
        int(x.split("_")[0][1:]),  # mois
        x
    )
)

df_hotel_monthly = df_hotel_monthly[hotel_cols_final + monthly_cols]

In [9]:
df_hotel_monthly

,HOTEL_NAME,HOTEL_CITY,HOTEL_LAT,HOTEL_LON,m01_FB_montant,m01_FB_nbr_ventes,m01_NON_FB_montant,m01_NON_FB_nbr_ventes,m02_FB_montant,m02_FB_nbr_ventes,m02_NON_FB_montant,m02_NON_FB_nbr_ventes,m03_FB_montant,m03_FB_nbr_ventes,m03_NON_FB_montant,m03_NON_FB_nbr_ventes,m04_FB_montant,m04_FB_nbr_ventes,m04_NON_FB_montant,m04_NON_FB_nbr_ventes,m05_FB_montant,m05_FB_nbr_ventes,m05_NON_FB_montant,m05_NON_FB_nbr_ventes,m06_FB_montant,m06_FB_nbr_ventes,m06_NON_FB_montant,m06_NON_FB_nbr_ventes,m07_FB_montant,m07_FB_nbr_ventes,m07_NON_FB_montant,m07_NON_FB_nbr_ventes,m08_FB_montant,m08_FB_nbr_ventes,m08_NON_FB_montant,m08_NON_FB_nbr_ventes,m09_FB_montant,m09_FB_nbr_ventes,m09_NON_FB_montant,m09_NON_FB_nbr_ventes,m10_FB_montant,m10_FB_nbr_ventes,m10_NON_FB_montant,m10_NON_FB_nbr_ventes,m11_FB_montant,m11_FB_nbr_ventes,m11_NON_FB_montant,m11_NON_FB_nbr_ventes,m12_FB_montant,m12_FB_nbr_ventes,m12_NON_FB_montant,m12_NON_FB_nbr_ventes
0,Ibis budget Nice,Nice,43.667571,7.214308,557.5,146.0,132.0,9.0,470.5,131.0,26.00,3.0,1014.6,301.0,215.0,19.0,640.6,187.0,405.10,28.0,975.3,262.0,639.0,50.0,1460.1,396.0,1003.10,79.0,1661.20,438.0,1081.5,81.0,1762.8,451.0,1678.00,118.0,1368.8,367.0,1231.0,107.0,1102.3,292.0,696.00,59.0,672.3,190.0,123.00,13.0,569.9,152.0,89.0,8.0
1,Ibis budget Strasbourg Centre République,Strasbourg,48.585058,7.736591,1720.5,325.0,0.0,0.0,822.0,129.0,0.00,0.0,1461.5,306.0,0.0,0.0,1447.0,241.0,0.00,0.0,654.0,142.0,0.0,0.0,1709.0,311.0,0.00,0.0,1400.50,239.0,0.0,0.0,1723.5,347.0,0.00,0.0,636.0,162.0,0.0,0.0,1541.5,310.0,0.00,0.0,2117.5,382.0,0.00,0.0,3364.0,641.0,0.0,0.0
2,Mercure Paris Montmartre Sacré-Cœur,Paris,48.885240,2.330055,8704.0,623.0,188.3,17.0,8998.5,820.0,719.00,21.0,11098.0,1053.0,474.0,25.0,10201.0,924.0,739.00,27.0,7562.0,619.0,355.0,19.0,8693.0,833.0,406.00,13.0,6425.00,572.0,155.0,9.0,6680.0,467.0,172.00,8.0,11380.0,849.0,156.0,6.0,13398.0,962.0,186.50,10.0,8681.0,652.0,146.50,11.0,8493.0,653.0,313.3,21.0
3,Novotel Megève Mont-Blanc,Megève,45.859850,6.619478,1705.4,233.0,2848.7,136.0,1338.0,233.0,2918.55,162.0,954.5,171.0,2291.5,132.0,461.5,65.0,1305.55,66.0,473.4,62.0,1503.2,55.0,665.5,80.0,1491.85,72.0,1013.50,151.0,2123.1,101.0,1232.5,169.0,3411.45,166.0,522.3,80.0,2253.9,95.0,441.8,49.0,806.55,37.0,437.9,61.0,1913.75,83.0,1407.8,224.0,2480.3,121.0
4,Novotel Paris Tour Eiffel,Paris,48.849660,2.283704,18282.2,2256.0,3858.0,387.0,18028.7,2268.0,5220.00,528.0,18779.4,2469.0,4822.0,548.0,15211.1,1849.0,2825.00,303.0,12578.5,1549.0,2696.0,283.0,16949.0,1869.0,3986.00,358.0,21624.67,2230.0,4167.5,353.0,14124.2,1644.0,3553.00,336.0,11643.4,1526.0,3841.0,373.0,20319.3,2728.0,7184.00,698.0,17429.4,2362.0,6300.00,640.0,22327.4,2857.0,5782.0,596.0

In [65]:
# Arrondi des coordonnées
df_poi_clean["HOTEL_LAT"] = df_poi_clean["HOTEL_LAT"].round(5)
df_poi_clean["HOTEL_LON"] = df_poi_clean["HOTEL_LON"].round(5)

df_weather_clean["HOTEL_LAT"] = df_weather_clean["HOTEL_LAT"].round(5)
df_weather_clean["HOTEL_LON"] = df_weather_clean["HOTEL_LON"].round(5)

df_rod_clean["HOTEL_LAT"] = df_rod_clean["HOTEL_LAT"].round(5)
df_rod_clean["HOTEL_LON"] = df_rod_clean["HOTEL_LON"].round(5)

df_hotel_monthly["HOTEL_LAT"] = df_hotel_monthly["HOTEL_LAT"].round(5)
df_hotel_monthly["HOTEL_LON"] = df_hotel_monthly["HOTEL_LON"].round(5)

df_rod_clean["HOTEL_NAME"] = df_rod_clean["HOTEL_NAME"].replace({
    "IBIS BUDGET NICE CALIFORNIE" : "Ibis budget Nice",
    "IBIS BUDGET STRASBOURG REPUBLIQUE" : "Ibis budget Strasbourg Centre République",
    "NOVOTEL MEGEVE MONT BLANC" : "Novotel Megève Mont-Blanc",
    "NOVOTEL PARIS CENTRE TOUR EIFFEL": "Novotel Paris Tour Eiffel",
    "MERCURE MONTMARTRE SACRE COEUR": "Mercure Paris Montmartre Sacré-Cœur",
})

df_rod_clean = df_rod_clean.drop(["HOTEL_LAT", "HOTEL_LON"], axis = 1)

# =========================
# Merge POI + WEATHER
# =========================

df_final = df_poi_clean.merge(
    df_weather_clean,
    on=["HOTEL_LAT", "HOTEL_LON"],
    how="inner"
)



# =========================
# Merge avec SALES
# =========================

df_final = df_final.merge(
    df_hotel_monthly,
    on=["HOTEL_NAME", "HOTEL_CITY", "HOTEL_LAT", "HOTEL_LON"],
    how="inner"
)

# =========================
# Merge avec ROD
# =========================
df_final = df_final.merge(
    df_rod_clean,
    on=["HOTEL_NAME"],
    how="inner"
)

In [66]:
df_final

                                 HOTEL_NAME  HOTEL_CITY  HOTEL_LAT  HOTEL_LON  \
0                          Ibis budget Nice        Nice   43.66757    7.21431
1  Ibis budget Strasbourg Centre République  Strasbourg   48.58506    7.73659
2       Mercure Paris Montmartre Sacré-Cœur       Paris   48.88524    2.33006
3                 Novotel Megève Mont-Blanc      Megève   45.85985    6.61948
4                 Novotel Paris Tour Eiffel       Paris   48.84966    2.28370

   fb_0_1km  fb_0_2km  fb_0_3km  fb_0_4km  fb_0_5km  not_fb_0_1km  \
0         0         0         0         3         3             3
1         0        30        60       102       120             0
2         6        12        57       123       195             3
3         3         3         6         6        15             0
4         3         6         9        36        69             0

   not_fb_0_2km  not_fb_0_3km  not_fb_0_4km  not_fb_0_5km  m01_dwpt_max  \
0             3             6             6             6          11.7
1             3             3            24            36          10.9
2             3            27            45            54          12.0
3             0             3             3             3           7.8
4             9            12            15            18          12.0

   m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  \
0          13.8          10.1          11.7          13.8          10.1
1          10.1           8.1          10.9          10.1           8.1
2          10.2           8.9          12.0          10.2           8.9
3           7.3           2.1           7.8           7.3           2.1
4          10.2           8.9          12.0          10.2           8.9

   m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_mean  m01_dwpt_mean  \
0          11.7          13.8          10.1       4.190188       4.944220
1          10.9          10.1           8.1       0.284812       0.931855
2          12.0          10.2           8.9       1.649194       2.165860
3           7.8           7.3           2.1      -4.595161      -5.025941
4          12.0          10.2           8.9       1.649194       2.165860

   m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  \
0       2.316801       4.190188       4.944220       2.316801       4.190188
1      -0.064382       0.284812       0.931855      -0.064382       0.284812
2       2.820565       1.649194       2.165860       2.820565       1.649194
3      -6.830242      -4.595161      -5.025941      -6.830242      -4.595161
4       2.820565       1.649194       2.165860       2.820565       1.649194

   m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_median  m01_dwpt_median  \
0       4.944220       2.316801             4.85              6.0
1       0.931855      -0.064382             0.00              0.1
2       2.165860       2.820565             0.95              1.9
3      -5.025941      -6.830242            -3.00             -3.4
4       2.165860       2.820565             0.95              1.9

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  \
0              3.1             4.85              6.0              3.1
1              0.0             0.00              0.1              0.0
2              3.5             0.95              1.9              3.5
3             -4.8            -3.00             -3.4             -4.8
4              3.5             0.95              1.9              3.5

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_min  \
0             4.85              6.0              3.1          -7.7
1             0.00              0.1              0.0          -9.8
2             0.95              1.9              3.5          -7.9
3            -3.00             -3.4             -4.8         -29.7
4             0.95              1.9              3.5          -7.9

   m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  \
0          -7.8         -11.7          -7.7          -7.8         -11.7
1          -6.0         -11.1          -9.8          -6.0         -11.1
2          -5.2          -6.5          -7.9          -5.2          -6.5
3         -23.9         -27.9         -29.7         -23.9         -27.9
4          -5.2          -6.5          -7.9          -5.2          -6.5

   m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_q25  m01_dwpt_q25  \
0          -7.7          -7.8         -11.7          2.10           2.7
1          -9.8          -6.0         -11.1         -4.30          -1.4
2          -7.9          -5.2          -6.5         -3.20          -0.6
3         -29.7         -23.9         -27.9         -7.65          -9.5
4          -7.9          -5.2          -6.5         -3.20          -0.6

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  \
0        -0.900          2.10           2.7        -0.900          2.10
1        -2.000         -4.30          -1.4        -2.000         -4.30
2         0.200         -3.20          -0.6         0.200         -3.20
3       -10.325         -7.65          -9.5       -10.325         -7.65
4         0.200         -3.20          -0.6         0.200         -3.20

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  \
0           2.7        -0.900         6.900         8.000           6.0
1          -1.4        -2.000         4.825         3.100           3.0
2          -0.6         0.200         6.300         4.725           5.8
3          -9.5       -10.325         0.500         0.600          -2.0
4          -0.6         0.200         6.300         4.725           5.8

   m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  \
0         6.900         8.000           6.0         6.900         8.000
1         4.825         3.100           3.0         4.825         3.100
2         6.300         4.725           5.8         6.300         4.725
3         0.500         0.600          -2.0         0.500         0.600
4         6.300         4.725           5.8         6.300         4.725

   m01_dwpt_q75  m01_index  m01_index  m01_index  m01_index  m01_index  \
0           6.0          5         17         29          5         17
1           3.0         71         83         95         71         83
2           5.8        137        149        161        137        149
3          -2.0         38         50         62         38         50
4           5.8        104        116        128        104        116

   m01_index  m01_index  m01_index  m01_index  m01_prcp_max  m01_prcp_max  \
0         29          5         17         29           8.0          24.9
1         95         71         83         95           2.6           3.0
2        161        137        149        161           2.0           4.4
3         62         38         50         62           4.3           7.9
4        128        104        116        128           2.0           4.4

   m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  \
0           5.2           8.0          24.9           5.2           8.0
1           2.2           2.6           3.0           2.2           2.6
2           3.2           2.0           4.4           3.2           2.0
3           4.1           4.3           7.9           4.1           4.3
4           3.2           2.0           4.4           3.2           2.0

   m01_prcp_max  m01_prcp_max  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  \
0          24.9           5.2       0.091263       0.201344       0.126075
1           3.0           2.2       0.059274       0.099462       0.075806
2           4.4           3.2       0.082392       0.145565       0.063710
3           7.9           4.1       0.229435       0.342339       0.183871
4           4.4           3.2       0.084812       0.145833       0.063710

   m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  \
0       0.091263       0.201344       0.126075       0.091263       0.201344
1       0.059274       0.099462       0.075806       0.059274       0.099462
2       0.082392       0.145565       0.063710       0.082392       0.145565
3       0.229435       0.342339       0.183871       0.229435       0.342339
4       0.084812       0.145833       0.063710       0.084812       0.145833

   m01_prcp_mean  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0       0.126075              0.0              0.0              0.0
1       0.075806              0.0              0.0              0.0
2       0.063710              0.0              0.0              0.0
3       0.183871              0.0              0.0              0.0
4       0.063710              0.0              0.0              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_min  m01_prcp_min  m01_prcp_min  \
0              0.0              0.0           0.0           0.0           0.0
1              0.0              0.0           0.0           0.0           0.0
2              0.0              0.0           0.0           0.0           0.0
3              0.0              0.0           0.0           0.0           0.0
4              0.0              0.0           0.0           0.0           0.0

   m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_min  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.2           0.0           0.0           0.2
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_pres_max  \
0           0.0           0.0           0.0           0.0        1035.9
1           0.0           0.0           0.0           0.0        1039.0
2           0.0           0.0           0.0           0.0        1037.6
3           0.0           0.0           0.2           0.0        1038.7
4           0.0           0.0           0.0           0.0        1037.6

   m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  \
0        1032.4        1023.4        1035.9        1032.4        1023.4
1        1041.9        1027.5        1039.0        1041.9        1027.5
2        1043.0        1024.6        1037.6        1043.0        1024.6
3        1033.7        1026.2        1038.7        1033.7        1026.2
4        1043.0        1024.6        1037.6        1043.0        1024.6

   m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_mean  m01_pres_mean  \
0        1035.9        1032.4        1023.4    1018.031317    1017.613306
1        1039.0        1041.9        1027.5    1021.235081    1018.150806
2        1037.6        1043.0        1024.6    1020.317070    1016.565054
3        1038.7        1033.7        1026.2    1020.037097    1018.511290
4        1037.6        1043.0        1024.6    1020.317070    1016.565054

   m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  \
0    1007.990323    1018.031317    1017.613306    1007.990323    1018.031317
1    1009.160349    1021.235081    1018.150806    1009.160349    1021.235081
2    1006.609409    1020.317070    1016.565054    1006.609409    1020.317070
3    1010.418683    1020.037097    1018.511290    1010.418683    1020.037097
4    1006.609409    1020.317070    1016.565054    1006.609409    1020.317070

   m01_pres_mean  m01_pres_mean  m01_pres_median  m01_pres_median  \
0    1017.613306    1007.990323          1020.05          1017.85
1    1018.150806    1009.160349          1027.00          1019.00
2    1016.565054    1006.609409          1025.65          1017.85
3    1018.511290    1010.418683          1020.00          1018.50
4    1016.565054    1006.609409          1025.65          1017.85

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median  \
0           1006.0          1020.05          1017.85           1006.0
1           1011.0          1027.00          1019.00           1011.0
2           1009.6          1025.65          1017.85           1009.6
3           1011.9          1020.00          1018.50           1011.9
4           1009.6          1025.65          1017.85           1009.6

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_min  \
0          1020.05          1017.85           1006.0         996.1
1          1027.00          1019.00           1011.0         987.4
2          1025.65          1017.85           1009.6         984.5
3          1020.00          1018.50           1011.9         993.2
4          1025.65          1017.85           1009.6         984.5

   m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  \
0         998.0         989.0         996.1         998.0         989.0
1         993.7         991.0         987.4         993.7         991.0
2         984.9         988.9         984.5         984.9         988.9
3         999.7         991.5         993.2         999.7         991.5
4         984.9         988.9         984.5         984.9         988.9

   m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_q25  m01_pres_q25  \
0         996.1         998.0         989.0      1008.200        1013.0
1         987.4         993.7         991.0      1010.975        1008.0
2         984.5         984.9         988.9      1011.000        1005.1
3         993.2         999.7         991.5      1011.700        1013.1
4         984.5         984.9         988.9      1011.000        1005.1

   m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  \
0      1000.000      1008.200        1013.0      1000.000      1008.200
1      1000.300      1010.975        1008.0      1000.300      1010.975
2       997.175      1011.000        1005.1       997.175      1011.000
3      1001.300      1011.700        1013.1      1001.300      1011.700
4       997.175      1011.000        1005.1       997.175      1011.000

   m01_pres_q25  m01_pres_q25  m01_pres_q75  m01_pres_q75  m01_pres_q75  \
0        1013.0      1000.000        1028.8        1022.0      1017.000
1        1008.0      1000.300        1031.6        1029.0      1016.900
2        1005.1       997.175        1029.4        1028.5      1014.325
3        1013.1      1001.300        1030.0        1024.7      1018.200
4        1005.1       997.175        1029.4        1028.5      1014.325

   m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  \
0        1028.8        1022.0      1017.000        1028.8        1022.0
1        1031.6        1029.0      1016.900        1031.6        1029.0
2        1029.4        1028.5      1014.325        1029.4        1028.5
3        1030.0        1024.7      1018.200        1030.0        1024.7
4        1029.4        1028.5      1014.325        1029.4        1028.5

   m01_pres_q75  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  \
0      1017.000          96.0         100.0         100.0          96.0
1      1016.900         100.0         100.0         100.0         100.0
2      1014.325          97.0         100.0         100.0          97.0
3      1018.200         100.0          99.0          97.0         100.0
4      1014.325          97.0         100.0         100.0          97.0

   m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  \
0         100.0         100.0          96.0         100.0         100.0
1         100.0         100.0         100.0         100.0         100.0
2         100.0         100.0          97.0         100.0         100.0
3          99.0          97.0         100.0          99.0          97.0
4         100.0         100.0          97.0         100.0         100.0

   m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0      68.086022      69.806452      63.106183      68.086022      69.806452
1      83.168011      84.180108      88.721774      83.168011      84.180108
2      79.572581      86.268817      86.686828      79.572581      86.268817
3      69.505376      70.672043      71.147849      69.505376      70.672043
4      79.572581      86.268817      86.686828      79.572581      86.268817

   m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0      63.106183      68.086022      69.806452      63.106183
1      88.721774      83.168011      84.180108      88.721774
2      86.686828      79.572581      86.268817      86.686828
3      71.147849      69.505376      70.672043      71.147849
4      86.686828      79.572581      86.268817      86.686828

   m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0             69.0             69.5             62.0             69.0
1             85.0             87.0             92.0             85.0
2             81.0             87.5             88.0             81.0
3             84.0             80.0             79.0             84.0
4             81.0             87.5             88.0             81.0

   m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0             69.5             62.0             69.0             69.5
1             87.0             92.0             85.0             87.0
2             87.5             88.0             81.0             87.5
3             80.0             79.0             84.0             80.0
4             87.5             88.0             81.0             87.5

   m01_rhum_median  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0             62.0          24.0          28.0          17.0          24.0
1             92.0          54.0          46.0          56.0          54.0
2             88.0          41.0          59.0          59.0          41.0
3             79.0           7.0          16.0          20.0           7.0
4             88.0          41.0          59.0          59.0          41.0

   m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0          28.0          17.0          24.0          28.0          17.0
1          46.0          56.0          54.0          46.0          56.0
2          59.0          59.0          41.0          59.0          59.0
3          16.0          20.0           7.0          16.0          20.0

In [91]:
df_final

                                 HOTEL_NAME  HOTEL_CITY  HOTEL_LAT  HOTEL_LON  \
0                          Ibis budget Nice        Nice   43.66757    7.21431
1  Ibis budget Strasbourg Centre République  Strasbourg   48.58506    7.73659
2       Mercure Paris Montmartre Sacré-Cœur       Paris   48.88524    2.33006
3                 Novotel Megève Mont-Blanc      Megève   45.85985    6.61948
4                 Novotel Paris Tour Eiffel       Paris   48.84966    2.28370

   fb_0_1km  fb_0_2km  fb_0_3km  fb_0_4km  fb_0_5km  not_fb_0_1km  \
0         0         0         0         3         3             3
1         0        30        60       102       120             0
2         6        12        57       123       195             3
3         3         3         6         6        15             0
4         3         6         9        36        69             0

   not_fb_0_2km  not_fb_0_3km  not_fb_0_4km  not_fb_0_5km  m01_dwpt_max  \
0             3             6             6             6          11.7
1             3             3            24            36          10.9
2             3            27            45            54          12.0
3             0             3             3             3           7.8
4             9            12            15            18          12.0

   m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  \
0          13.8          10.1          11.7          13.8          10.1
1          10.1           8.1          10.9          10.1           8.1
2          10.2           8.9          12.0          10.2           8.9
3           7.3           2.1           7.8           7.3           2.1
4          10.2           8.9          12.0          10.2           8.9

   m01_dwpt_max  m01_dwpt_max  m01_dwpt_max  m01_dwpt_mean  m01_dwpt_mean  \
0          11.7          13.8          10.1       4.190188       4.944220
1          10.9          10.1           8.1       0.284812       0.931855
2          12.0          10.2           8.9       1.649194       2.165860
3           7.8           7.3           2.1      -4.595161      -5.025941
4          12.0          10.2           8.9       1.649194       2.165860

   m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_mean  \
0       2.316801       4.190188       4.944220       2.316801       4.190188
1      -0.064382       0.284812       0.931855      -0.064382       0.284812
2       2.820565       1.649194       2.165860       2.820565       1.649194
3      -6.830242      -4.595161      -5.025941      -6.830242      -4.595161
4       2.820565       1.649194       2.165860       2.820565       1.649194

   m01_dwpt_mean  m01_dwpt_mean  m01_dwpt_median  m01_dwpt_median  \
0       4.944220       2.316801             4.85              6.0
1       0.931855      -0.064382             0.00              0.1
2       2.165860       2.820565             0.95              1.9
3      -5.025941      -6.830242            -3.00             -3.4
4       2.165860       2.820565             0.95              1.9

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  \
0              3.1             4.85              6.0              3.1
1              0.0             0.00              0.1              0.0
2              3.5             0.95              1.9              3.5
3             -4.8            -3.00             -3.4             -4.8
4              3.5             0.95              1.9              3.5

   m01_dwpt_median  m01_dwpt_median  m01_dwpt_median  m01_dwpt_min  \
0             4.85              6.0              3.1          -7.7
1             0.00              0.1              0.0          -9.8
2             0.95              1.9              3.5          -7.9
3            -3.00             -3.4             -4.8         -29.7
4             0.95              1.9              3.5          -7.9

   m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  \
0          -7.8         -11.7          -7.7          -7.8         -11.7
1          -6.0         -11.1          -9.8          -6.0         -11.1
2          -5.2          -6.5          -7.9          -5.2          -6.5
3         -23.9         -27.9         -29.7         -23.9         -27.9
4          -5.2          -6.5          -7.9          -5.2          -6.5

   m01_dwpt_min  m01_dwpt_min  m01_dwpt_min  m01_dwpt_q25  m01_dwpt_q25  \
0          -7.7          -7.8         -11.7          2.10           2.7
1          -9.8          -6.0         -11.1         -4.30          -1.4
2          -7.9          -5.2          -6.5         -3.20          -0.6
3         -29.7         -23.9         -27.9         -7.65          -9.5
4          -7.9          -5.2          -6.5         -3.20          -0.6

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q25  \
0        -0.900          2.10           2.7        -0.900          2.10
1        -2.000         -4.30          -1.4        -2.000         -4.30
2         0.200         -3.20          -0.6         0.200         -3.20
3       -10.325         -7.65          -9.5       -10.325         -7.65
4         0.200         -3.20          -0.6         0.200         -3.20

   m01_dwpt_q25  m01_dwpt_q25  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  \
0           2.7        -0.900         6.900         8.000           6.0
1          -1.4        -2.000         4.825         3.100           3.0
2          -0.6         0.200         6.300         4.725           5.8
3          -9.5       -10.325         0.500         0.600          -2.0
4          -0.6         0.200         6.300         4.725           5.8

   m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  m01_dwpt_q75  \
0         6.900         8.000           6.0         6.900         8.000
1         4.825         3.100           3.0         4.825         3.100
2         6.300         4.725           5.8         6.300         4.725
3         0.500         0.600          -2.0         0.500         0.600
4         6.300         4.725           5.8         6.300         4.725

   m01_dwpt_q75  m01_index  m01_index  m01_index  m01_index  m01_index  \
0           6.0          5         17         29          5         17
1           3.0         71         83         95         71         83
2           5.8        137        149        161        137        149
3          -2.0         38         50         62         38         50
4           5.8        104        116        128        104        116

   m01_index  m01_index  m01_index  m01_index  m01_prcp_max  m01_prcp_max  \
0         29          5         17         29           8.0          24.9
1         95         71         83         95           2.6           3.0
2        161        137        149        161           2.0           4.4
3         62         38         50         62           4.3           7.9
4        128        104        116        128           2.0           4.4

   m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  m01_prcp_max  \
0           5.2           8.0          24.9           5.2           8.0
1           2.2           2.6           3.0           2.2           2.6
2           3.2           2.0           4.4           3.2           2.0
3           4.1           4.3           7.9           4.1           4.3
4           3.2           2.0           4.4           3.2           2.0

   m01_prcp_max  m01_prcp_max  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  \
0          24.9           5.2       0.091263       0.201344       0.126075
1           3.0           2.2       0.059274       0.099462       0.075806
2           4.4           3.2       0.082392       0.145565       0.063710
3           7.9           4.1       0.229435       0.342339       0.183871
4           4.4           3.2       0.084812       0.145833       0.063710

   m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  m01_prcp_mean  \
0       0.091263       0.201344       0.126075       0.091263       0.201344
1       0.059274       0.099462       0.075806       0.059274       0.099462
2       0.082392       0.145565       0.063710       0.082392       0.145565
3       0.229435       0.342339       0.183871       0.229435       0.342339
4       0.084812       0.145833       0.063710       0.084812       0.145833

   m01_prcp_mean  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0       0.126075              0.0              0.0              0.0
1       0.075806              0.0              0.0              0.0
2       0.063710              0.0              0.0              0.0
3       0.183871              0.0              0.0              0.0
4       0.063710              0.0              0.0              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_median  m01_prcp_median  \
0              0.0              0.0              0.0              0.0
1              0.0              0.0              0.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   m01_prcp_median  m01_prcp_median  m01_prcp_min  m01_prcp_min  m01_prcp_min  \
0              0.0              0.0           0.0           0.0           0.0
1              0.0              0.0           0.0           0.0           0.0
2              0.0              0.0           0.0           0.0           0.0
3              0.0              0.0           0.0           0.0           0.0
4              0.0              0.0           0.0           0.0           0.0

   m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  m01_prcp_min  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_min  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  m01_prcp_q25  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.0           0.0           0.0           0.0
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  \
0           0.0           0.0           0.0           0.0           0.0
1           0.0           0.0           0.0           0.0           0.0
2           0.0           0.0           0.0           0.0           0.0
3           0.0           0.2           0.0           0.0           0.2
4           0.0           0.0           0.0           0.0           0.0

   m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_prcp_q75  m01_pres_max  \
0           0.0           0.0           0.0           0.0        1035.9
1           0.0           0.0           0.0           0.0        1039.0
2           0.0           0.0           0.0           0.0        1037.6
3           0.0           0.0           0.2           0.0        1038.7
4           0.0           0.0           0.0           0.0        1037.6

   m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_max  \
0        1032.4        1023.4        1035.9        1032.4        1023.4
1        1041.9        1027.5        1039.0        1041.9        1027.5
2        1043.0        1024.6        1037.6        1043.0        1024.6
3        1033.7        1026.2        1038.7        1033.7        1026.2
4        1043.0        1024.6        1037.6        1043.0        1024.6

   m01_pres_max  m01_pres_max  m01_pres_max  m01_pres_mean  m01_pres_mean  \
0        1035.9        1032.4        1023.4    1018.031317    1017.613306
1        1039.0        1041.9        1027.5    1021.235081    1018.150806
2        1037.6        1043.0        1024.6    1020.317070    1016.565054
3        1038.7        1033.7        1026.2    1020.037097    1018.511290
4        1037.6        1043.0        1024.6    1020.317070    1016.565054

   m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  m01_pres_mean  \
0    1007.990323    1018.031317    1017.613306    1007.990323    1018.031317
1    1009.160349    1021.235081    1018.150806    1009.160349    1021.235081
2    1006.609409    1020.317070    1016.565054    1006.609409    1020.317070
3    1010.418683    1020.037097    1018.511290    1010.418683    1020.037097
4    1006.609409    1020.317070    1016.565054    1006.609409    1020.317070

   m01_pres_mean  m01_pres_mean  m01_pres_median  m01_pres_median  \
0    1017.613306    1007.990323          1020.05          1017.85
1    1018.150806    1009.160349          1027.00          1019.00
2    1016.565054    1006.609409          1025.65          1017.85
3    1018.511290    1010.418683          1020.00          1018.50
4    1016.565054    1006.609409          1025.65          1017.85

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_median  \
0           1006.0          1020.05          1017.85           1006.0
1           1011.0          1027.00          1019.00           1011.0
2           1009.6          1025.65          1017.85           1009.6
3           1011.9          1020.00          1018.50           1011.9
4           1009.6          1025.65          1017.85           1009.6

   m01_pres_median  m01_pres_median  m01_pres_median  m01_pres_min  \
0          1020.05          1017.85           1006.0         996.1
1          1027.00          1019.00           1011.0         987.4
2          1025.65          1017.85           1009.6         984.5
3          1020.00          1018.50           1011.9         993.2
4          1025.65          1017.85           1009.6         984.5

   m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_min  \
0         998.0         989.0         996.1         998.0         989.0
1         993.7         991.0         987.4         993.7         991.0
2         984.9         988.9         984.5         984.9         988.9
3         999.7         991.5         993.2         999.7         991.5
4         984.9         988.9         984.5         984.9         988.9

   m01_pres_min  m01_pres_min  m01_pres_min  m01_pres_q25  m01_pres_q25  \
0         996.1         998.0         989.0      1008.200        1013.0
1         987.4         993.7         991.0      1010.975        1008.0
2         984.5         984.9         988.9      1011.000        1005.1
3         993.2         999.7         991.5      1011.700        1013.1
4         984.5         984.9         988.9      1011.000        1005.1

   m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  m01_pres_q25  \
0      1000.000      1008.200        1013.0      1000.000      1008.200
1      1000.300      1010.975        1008.0      1000.300      1010.975
2       997.175      1011.000        1005.1       997.175      1011.000
3      1001.300      1011.700        1013.1      1001.300      1011.700
4       997.175      1011.000        1005.1       997.175      1011.000

   m01_pres_q25  m01_pres_q25  m01_pres_q75  m01_pres_q75  m01_pres_q75  \
0        1013.0      1000.000        1028.8        1022.0      1017.000
1        1008.0      1000.300        1031.6        1029.0      1016.900
2        1005.1       997.175        1029.4        1028.5      1014.325
3        1013.1      1001.300        1030.0        1024.7      1018.200
4        1005.1       997.175        1029.4        1028.5      1014.325

   m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  m01_pres_q75  \
0        1028.8        1022.0      1017.000        1028.8        1022.0
1        1031.6        1029.0      1016.900        1031.6        1029.0
2        1029.4        1028.5      1014.325        1029.4        1028.5
3        1030.0        1024.7      1018.200        1030.0        1024.7
4        1029.4        1028.5      1014.325        1029.4        1028.5

   m01_pres_q75  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  \
0      1017.000          96.0         100.0         100.0          96.0
1      1016.900         100.0         100.0         100.0         100.0
2      1014.325          97.0         100.0         100.0          97.0
3      1018.200         100.0          99.0          97.0         100.0
4      1014.325          97.0         100.0         100.0          97.0

   m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  m01_rhum_max  \
0         100.0         100.0          96.0         100.0         100.0
1         100.0         100.0         100.0         100.0         100.0
2         100.0         100.0          97.0         100.0         100.0
3          99.0          97.0         100.0          99.0          97.0
4         100.0         100.0          97.0         100.0         100.0

   m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0      68.086022      69.806452      63.106183      68.086022      69.806452
1      83.168011      84.180108      88.721774      83.168011      84.180108
2      79.572581      86.268817      86.686828      79.572581      86.268817
3      69.505376      70.672043      71.147849      69.505376      70.672043
4      79.572581      86.268817      86.686828      79.572581      86.268817

   m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  m01_rhum_mean  \
0      63.106183      68.086022      69.806452      63.106183
1      88.721774      83.168011      84.180108      88.721774
2      86.686828      79.572581      86.268817      86.686828
3      71.147849      69.505376      70.672043      71.147849
4      86.686828      79.572581      86.268817      86.686828

   m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0             69.0             69.5             62.0             69.0
1             85.0             87.0             92.0             85.0
2             81.0             87.5             88.0             81.0
3             84.0             80.0             79.0             84.0
4             81.0             87.5             88.0             81.0

   m01_rhum_median  m01_rhum_median  m01_rhum_median  m01_rhum_median  \
0             69.5             62.0             69.0             69.5
1             87.0             92.0             85.0             87.0
2             87.5             88.0             81.0             87.5
3             80.0             79.0             84.0             80.0
4             87.5             88.0             81.0             87.5

   m01_rhum_median  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0             62.0          24.0          28.0          17.0          24.0
1             92.0          54.0          46.0          56.0          54.0
2             88.0          41.0          59.0          59.0          41.0
3             79.0           7.0          16.0          20.0           7.0
4             88.0          41.0          59.0          59.0          41.0

   m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  m01_rhum_min  \
0          28.0          17.0          24.0          28.0          17.0
1          46.0          56.0          54.0          46.0          56.0
2          59.0          59.0          41.0          59.0          59.0
3          16.0          20.0           7.0          16.0          20.0

In [111]:
ml_skip_columns= ["HOTEL_CODE", "HOTEL_NAME", "HOTEL_CITY", "HOTEL_LAT", "HOTEL_LON"]

pattern = r"^m\d{2}_.*(vente|montant).*"
ml_target_variables = list(set([
    col for col in df_final.columns
    if(bool(re.match(pattern, col)))
]))

ml_desc_variables = list(set([col for col in df_final.columns  if ((col not in ml_skip_columns) and (col not in ml_target_variables))]))

X = df_final[ml_desc_variables].fillna(0)
y = df_final[ml_target_variables]

In [112]:
m = keras.models.Sequential([
    keras.layers.InputLayer(shape = [X.shape[1]]),
    keras.layers.Dense(y.shape[1])
])

m.compile(loss = "mse", optimizer = "adam")

In [114]:
m.fit(X, y, batch_size = 1, epochs = 1000)

Epoch 1/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9434291.0000
Epoch 2/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9761992.0000
Epoch 3/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9345672.0000
Epoch 4/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9372672.0000
Epoch 5/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9486747.0000
Epoch 6/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9247579.0000
Epoch 7/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9324866.0000
Epoch 8/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9192097.0000
Epoch 9/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9186263.0000
Epoch 10/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9144471.0000
Epoch 11/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9247017.0000
Epoch 12/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9089150.0000
Epoch 13/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9309483.0000
Epoch 14/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9042989.0000
Epoch 15/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9050094.0000
Epoch 16/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8996857.0000
Epoch 17/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9029402.0000
Epoch 18/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8983154.0000
Epoch 19/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9142931.0000
Epoch 20/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8986533.0000
Epoch 21/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9169767.0000
Epoch 22/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9198989.0000
Epoch 23/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8929570.0000
Epoch 24/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8883978.0000
Epoch 25/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8843409.0000
Epoch 26/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8767546.0000
Epoch 27/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8831714.0000
Epoch 28/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8811837.0000
Epoch 29/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8825814.0000
Epoch 30/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8894137.0000
Epoch 31/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8724601.0000
Epoch 32/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8931442.0000
Epoch 33/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8836594.0000
Epoch 34/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8819610.0000
Epoch 35/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8943472.0000
Epoch 36/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8596199.0000
Epoch 37/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 8835761.0000
Epoch 38/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8609593.0000
Epoch 39/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8810691.0000
Epoch 40/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8671765.0000
Epoch 41/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8833638.0000
Epoch 42/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8523631.0000
Epoch 43/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8496471.0000
Epoch 44/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8517627.0000
Epoch 45/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8809326.0000
Epoch 46/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8444404.0000
Epoch 47/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8427974.0000
Epoch 48/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8410983.0000
Epoch 49/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8416622.0000
Epoch 50/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8417035.0000
Epoch 51/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8356403.0000
Epoch 52/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8517569.0000
Epoch 53/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8339074.5000
Epoch 54/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8525767.0000
Epoch 55/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8329812.0000
Epoch 56/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8442454.0000
Epoch 57/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8443286.0000
Epoch 58/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 8345054.5000
Epoch 59/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8437302.0000
Epoch 60/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8299473.0000
Epoch 61/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8192653.0000
Epoch 62/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8180513.5000
Epoch 63/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8151181.0000
Epoch 64/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8154640.0000
Epoch 65/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8307573.0000
Epoch 66/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8126170.5000
Epoch 67/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8298048.0000
Epoch 68/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8185124.0000
Epoch 69/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8221742.5000
Epoch 70/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8334185.5000
Epoch 71/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8066742.5000
Epoch 72/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8110402.5000
Epoch 73/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7987364.0000
Epoch 74/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7951465.0000
Epoch 75/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8041361.5000
Epoch 76/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8061767.0000
Epoch 77/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7932690.5000
Epoch 78/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7912380.0000
Epoch 79/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7848581.5000
Epoch 80/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7914835.0000
Epoch 81/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7952918.5000
Epoch 82/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7780232.0000
Epoch 83/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7868860.0000
Epoch 84/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8051385.0000
Epoch 85/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7823309.5000
Epoch 86/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8194220.0000
Epoch 87/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7774129.5000
Epoch 88/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7861503.0000
Epoch 89/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7759862.5000
Epoch 90/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7731155.0000
Epoch 91/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7843155.0000
Epoch 92/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7875616.0000
Epoch 93/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7892808.0000
Epoch 94/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7845803.0000
Epoch 95/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7725624.0000
Epoch 96/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7683360.0000
Epoch 97/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7975784.0000
Epoch 98/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7640749.0000
Epoch 99/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7588532.0000
Epoch 100/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7756557.0000
Epoch 101/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7582729.0000
Epoch 102/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7750428.0000
Epoch 103/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7520548.0000
Epoch 104/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7519733.0000
Epoch 105/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7517133.5000
Epoch 106/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7497046.5000
Epoch 107/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7534895.0000
Epoch 108/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7522746.5000
Epoch 109/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7420727.0000
Epoch 110/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7607241.5000
Epoch 111/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7683368.0000
Epoch 112/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7388163.0000
Epoch 113/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7425854.5000
Epoch 114/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7392762.5000
Epoch 115/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7320649.5000
Epoch 116/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7423985.5000
Epoch 117/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7288957.0000
Epoch 118/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7444025.0000
Epoch 119/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7360416.0000
Epoch 120/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7401097.5000
Epoch 121/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7323120.0000
Epoch 122/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7279979.0000
Epoch 123/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7424602.5000
Epoch 124/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7256821.0000
Epoch 125/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7450914.5000
Epoch 126/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7319632.0000
Epoch 127/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7445871.0000
Epoch 128/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7218453.5000
Epoch 129/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7343258.5000
Epoch 130/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7198856.0000
Epoch 131/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7154345.5000
Epoch 132/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7111074.5000
Epoch 133/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7216984.0000
Epoch 134/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7115706.5000
Epoch 135/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7061861.0000
Epoch 136/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7055872.0000
Epoch 137/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7064844.0000
Epoch 138/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7098611.0000
Epoch 139/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7036472.0000
Epoch 140/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7302001.5000
Epoch 141/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 7027064.0000
Epoch 142/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7001781.5000
Epoch 143/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7011340.0000
Epoch 144/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7284393.5000
Epoch 145/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7070013.0000
Epoch 146/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6905905.5000
Epoch 147/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6891889.5000
Epoch 148/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6987788.0000
Epoch 149/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6918241.5000
Epoch 150/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7124242.5000
Epoch 151/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6970982.5000
Epoch 152/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6995403.0000
Epoch 153/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6909149.0000
Epoch 154/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6881144.0000
Epoch 155/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7194591.0000
Epoch 156/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6970937.0000
Epoch 157/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7042358.5000
Epoch 158/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6815875.0000
Epoch 159/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6856591.0000
Epoch 160/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6833669.5000
Epoch 161/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6820153.5000
Epoch 162/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6817589.5000
Epoch 163/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6772272.0000
Epoch 164/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6717174.5000
Epoch 165/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6820680.0000
Epoch 166/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6731365.5000
Epoch 167/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6752641.0000
Epoch 168/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6803365.0000
Epoch 169/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6667347.5000
Epoch 170/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6620624.5000
Epoch 171/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6646705.5000
Epoch 172/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6749890.5000
Epoch 173/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 6649292.5000
Epoch 174/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6744743.0000
Epoch 175/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6703523.5000
Epoch 176/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6613883.0000
Epoch 177/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6694400.5000
Epoch 178/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6588071.0000
Epoch 179/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6801093.0000
Epoch 180/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6584560.5000
Epoch 181/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6613397.0000
Epoch 182/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6505419.0000
Epoch 183/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6797317.0000
Epoch 184/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6761366.5000
Epoch 185/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6737135.0000
Epoch 186/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6513279.0000
Epoch 187/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6521516.0000
Epoch 188/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6457103.0000
Epoch 189/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6477891.5000
Epoch 190/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6435546.5000
Epoch 191/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6427006.0000
Epoch 192/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6435593.5000
Epoch 193/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6444890.0000
Epoch 194/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6559580.0000
Epoch 195/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6396891.5000
Epoch 196/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6429007.0000
Epoch 197/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6365954.0000
Epoch 198/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6361968.0000
Epoch 199/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6552814.5000
Epoch 200/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6412484.0000
Epoch 201/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 6447842.0000
Epoch 202/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6349991.0000
Epoch 203/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6452262.0000
Epoch 204/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6371913.0000
Epoch 205/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6344593.5000
Epoch 206/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6335548.0000
Epoch 207/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6375323.0000
Epoch 208/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6423519.5000
Epoch 209/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6374784.5000
Epoch 210/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6334236.0000
Epoch 211/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6260690.0000
Epoch 212/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6238824.0000
Epoch 213/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6289478.5000
Epoch 214/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6282943.0000
Epoch 215/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6313913.0000
Epoch 216/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6331647.5000
Epoch 217/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6270457.0000
Epoch 218/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6189305.5000
Epoch 219/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6316076.5000
Epoch 220/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6221748.0000
Epoch 221/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6559954.0000
Epoch 222/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6173851.0000
Epoch 223/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6192622.0000
Epoch 224/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6155616.0000
Epoch 225/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6138852.5000
Epoch 226/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6136254.5000
Epoch 227/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6119062.0000
Epoch 228/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6107381.5000
Epoch 229/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6086965.0000
Epoch 230/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6139591.0000
Epoch 231/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6077493.5000
Epoch 232/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6147581.0000
Epoch 233/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6181717.0000
Epoch 234/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6210113.0000
Epoch 235/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6072477.5000
Epoch 236/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6160340.0000
Epoch 237/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6237803.5000
Epoch 238/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6001294.0000
Epoch 239/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6023869.0000
Epoch 240/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5987635.0000
Epoch 241/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5968746.5000
Epoch 242/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5924550.5000
Epoch 243/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5988421.0000
Epoch 244/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5975883.0000
Epoch 245/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6018147.5000
Epoch 246/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5981117.5000
Epoch 247/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5963436.5000
Epoch 248/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5917009.0000
Epoch 249/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5913063.5000
Epoch 250/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6019952.0000
Epoch 251/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5958840.5000
Epoch 252/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5983654.0000
Epoch 253/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5927455.0000
Epoch 254/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5945078.5000
Epoch 255/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5900302.5000
Epoch 256/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6044803.0000
Epoch 257/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6005696.5000
Epoch 258/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5946023.0000
Epoch 259/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5870170.5000
Epoch 260/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5912083.5000
Epoch 261/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 5850938.0000
Epoch 262/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5910246.5000
Epoch 263/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5831041.5000
Epoch 264/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5766036.5000
Epoch 265/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6046580.0000
Epoch 266/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5866201.5000
Epoch 267/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5845254.5000
Epoch 268/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5843759.0000
Epoch 269/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5768317.5000
Epoch 270/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5761889.0000
Epoch 271/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5822347.5000
Epoch 272/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5737673.5000
Epoch 273/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5733535.0000
Epoch 274/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5748907.5000
Epoch 275/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5706941.5000

In [116]:
m.fit(X, y, batch_size = 1, epochs = 10000)

Epoch 1/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1262.9412
Epoch 2/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2453.7954
Epoch 3/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1899.1707
Epoch 4/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2457.7524
Epoch 5/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2168.5422
Epoch 6/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 745.8651
Epoch 7/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 714.5196
Epoch 8/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 992.8602
Epoch 9/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 843.5859
Epoch 10/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1103.8976
Epoch 11/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 858.4625
Epoch 12/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 774.7701
Epoch 13/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 857.3138
Epoch 14/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1452.4352
Epoch 15/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 878.7506
Epoch 16/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 827.2609
Epoch 17/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 723.0978
Epoch 18/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 698.1598
Epoch 19/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 580.2496
Epoch 20/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 533.9968
Epoch 21/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 463.1366
Epoch 22/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 642.7772
Epoch 23/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 983.0941
Epoch 24/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1500.7635
Epoch 25/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1167.8932
Epoch 26/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 556.2784
Epoch 27/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 833.9751
Epoch 28/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1345.6559
Epoch 29/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1017.1625
Epoch 30/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1231.6819
Epoch 31/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2046.3616
Epoch 32/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 920.3948
Epoch 33/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 482.9896
Epoch 34/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 699.8326
Epoch 35/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1601.2946
Epoch 36/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 850.2533
Epoch 37/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 878.9077
Epoch 38/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1702.5365
Epoch 39/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 883.4818
Epoch 40/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1120.5804
Epoch 41/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1606.8611
Epoch 42/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3472.8843
Epoch 43/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2370.5537
Epoch 44/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1613.0062
Epoch 45/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2056.6189
Epoch 46/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2567.0347
Epoch 47/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2432.7864
Epoch 48/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2821.2036
Epoch 49/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2285.0051
Epoch 50/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2635.8633
Epoch 51/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2105.0793
Epoch 52/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1318.0244
Epoch 53/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1808.8596
Epoch 54/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2478.6929
Epoch 55/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2075.9844
Epoch 56/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2239.0698
Epoch 57/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1884.9545
Epoch 58/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 980.8678
Epoch 59/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1891.8636
Epoch 60/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2285.0269
Epoch 61/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2412.6516
Epoch 62/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3089.1292
Epoch 63/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 4653.6260
Epoch 64/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 3784.7825
Epoch 65/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3968.9082
Epoch 66/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2484.4932
Epoch 67/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3173.6860
Epoch 68/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2230.2314
Epoch 69/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1968.8031
Epoch 70/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1267.1687
Epoch 71/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2020.4578
Epoch 72/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2356.2046
Epoch 73/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1920.2533
Epoch 74/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4034.0625
Epoch 75/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4387.2178
Epoch 76/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15261.2480
Epoch 77/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 16778.1621
Epoch 78/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 9413.7373
Epoch 79/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6741.3828
Epoch 80/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5619.9014
Epoch 81/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6644.6343
Epoch 82/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8017.5352
Epoch 83/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9526.8984
Epoch 84/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4174.9688
Epoch 85/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8610.7832
Epoch 86/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3907.7903
Epoch 87/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3025.1550
Epoch 88/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2536.4028
Epoch 89/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3776.6946
Epoch 90/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3221.4294
Epoch 91/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2233.5083
Epoch 92/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2696.5176
Epoch 93/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2590.6812
Epoch 94/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3838.1484
Epoch 95/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 4369.7412
Epoch 96/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3314.4351
Epoch 97/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4023.1926
Epoch 98/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2904.4695
Epoch 99/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2616.7014
Epoch 100/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2257.9585
Epoch 101/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1437.3171
Epoch 102/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2850.0547
Epoch 103/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2935.8057
Epoch 104/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1959.8959
Epoch 105/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2620.2144
Epoch 106/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3979.4624
Epoch 107/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4784.6494
Epoch 108/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3032.0876
Epoch 109/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2336.8279
Epoch 110/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2019.9783
Epoch 111/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3138.0388
Epoch 112/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4718.2480
Epoch 113/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2107.7866
Epoch 114/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1453.8452
Epoch 115/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1751.7992
Epoch 116/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1317.0334
Epoch 117/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1617.5406
Epoch 118/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1522.4098
Epoch 119/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2551.9836
Epoch 120/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1907.3201
Epoch 121/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2674.7590
Epoch 122/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2075.7417
Epoch 123/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4149.0698
Epoch 124/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4582.3618
Epoch 125/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5219.3809
Epoch 126/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 5943.1104
Epoch 127/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5883.4609
Epoch 128/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 5539.4956
Epoch 129/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 4011.2515
Epoch 130/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2845.5117
Epoch 131/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3385.2817
Epoch 132/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4126.5342
Epoch 133/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6783.3828
Epoch 134/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6035.3320
Epoch 135/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 5078.9380
Epoch 136/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 13282.9277
Epoch 137/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 8979.0566
Epoch 138/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 5290.4385
Epoch 139/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3088.1375
Epoch 140/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2806.2463
Epoch 141/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1954.5387
Epoch 142/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1467.3193
Epoch 143/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2008.3571
Epoch 144/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4160.6553
Epoch 145/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2933.0605
Epoch 146/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2928.2664
Epoch 147/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2679.7559
Epoch 148/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1262.5576
Epoch 149/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1079.6936
Epoch 150/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1331.6648
Epoch 151/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1420.2682
Epoch 152/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1246.4587
Epoch 153/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 982.2405
Epoch 154/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1172.8025
Epoch 155/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 685.9644
Epoch 156/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 719.7098
Epoch 157/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 943.7181
Epoch 158/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 996.2455
Epoch 159/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1808.2012
Epoch 160/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3730.7742
Epoch 161/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4154.8076
Epoch 162/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2703.9475
Epoch 163/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1202.5413
Epoch 164/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2029.9557
Epoch 165/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1032.8376
Epoch 166/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1888.5521
Epoch 167/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1318.9719
Epoch 168/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2806.6296
Epoch 169/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1800.4114
Epoch 170/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1588.4071
Epoch 171/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2172.1384
Epoch 172/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1954.4241
Epoch 173/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1763.9261
Epoch 174/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3430.8137
Epoch 175/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1698.7633
Epoch 176/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 800.3519
Epoch 177/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1435.5476
Epoch 178/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2300.7078
Epoch 179/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1539.4822
Epoch 180/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 866.6855
Epoch 181/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1267.2653
Epoch 182/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 550.5494
Epoch 183/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 763.5226
Epoch 184/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 882.6248
Epoch 185/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 814.1837
Epoch 186/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 589.6915
Epoch 187/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 383.5817
Epoch 188/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 589.9211
Epoch 189/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1103.5066
Epoch 190/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1771.0664
Epoch 191/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1344.6882
Epoch 192/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 554.5306
Epoch 193/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 533.7791
Epoch 194/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 364.9829
Epoch 195/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 446.5069
Epoch 196/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 401.6310
Epoch 197/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 501.8409
Epoch 198/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 242.8803
Epoch 199/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 300.4944
Epoch 200/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 322.3379
Epoch 201/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 217.1829
Epoch 202/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 204.8741
Epoch 203/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 273.0698
Epoch 204/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 668.1149
Epoch 205/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1204.3330
Epoch 206/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1350.7747
Epoch 207/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1085.2173
Epoch 208/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 989.9805
Epoch 209/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1575.6553
Epoch 210/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 768.3676
Epoch 211/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 515.4291
Epoch 212/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 316.9101
Epoch 213/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 224.0077
Epoch 214/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 398.9909
Epoch 215/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 925.0391
Epoch 216/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 988.1312
Epoch 217/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 910.1125
Epoch 218/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1499.0383
Epoch 219/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 629.7528
Epoch 220/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 604.8495
Epoch 221/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 568.4335
Epoch 222/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 491.8113
Epoch 223/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 423.9223
Epoch 224/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 738.7657
Epoch 225/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 476.4706
Epoch 226/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 924.2192
Epoch 227/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 441.4482
Epoch 228/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 272.2883
Epoch 229/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 123.0326
Epoch 230/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 163.0651
Epoch 231/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 228.4936
Epoch 232/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 186.7464
Epoch 233/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 144.2320
Epoch 234/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 113.2919
Epoch 235/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 72.4009
Epoch 236/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 80.3709
Epoch 237/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 125.6122
Epoch 238/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 77.9767
Epoch 239/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 118.9631
Epoch 240/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 153.3372
Epoch 241/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 109.7262
Epoch 242/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 89.3863
Epoch 243/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 64.4216
Epoch 244/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 183.3849
Epoch 245/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 160.3178
Epoch 246/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 283.4720
Epoch 247/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 99.1918
Epoch 248/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 177.8475
Epoch 249/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 154.8793
Epoch 250/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 95.4432
Epoch 251/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68.7605
Epoch 252/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 81.8511
Epoch 253/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 68.5688
Epoch 254/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 192.4852
Epoch 255/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 191.9904
Epoch 256/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 480.2285
Epoch 257/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 506.8939
Epoch 258/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 423.8373
Epoch 259/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 783.7512
Epoch 260/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 526.8524
Epoch 261/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 585.6667
Epoch 262/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 892.8170
Epoch 263/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 965.0275
Epoch 264/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 586.4117
Epoch 265/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 874.2231
Epoch 266/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1062.0256
Epoch 267/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 761.2716
Epoch 268/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 626.5148
Epoch 269/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 400.5529
Epoch 270/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 803.9350
Epoch 271/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 552.5989
Epoch 272/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 324.9887
Epoch 273/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 612.6002
Epoch 274/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 444.6961
Epoch 275/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 290.4554
Epoch 276/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 210.6446
Epoch 277/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 276.8197
Epoch 278/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 394.3978
Epoch 279/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 324.1982
Epoch 280/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 508.8621
Epoch 281/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 336.4049
Epoch 282/10000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 305.7288